/* ═══════════════════════════════════════════════
   VOCABULAIRE THÉMATIQUE — A1
   Toutes les strings en backticks `...`
   ~350 mots répartis en 10 thèmes
═══════════════════════════════════════════════ */
'use strict';

var A1_VOCAB_THEMATIC = [
  {
    theme:`الأُسْرَةُ الْمُمْتَدَّةُ — Famille élargie`,
    words:[
      {w:`زَوْج`,p:`زوج`,tr:`zawj`,fr:`mari, époux`,fm:`Nom — schème فَعْل`,root:`ز و ج`},
      {w:`زَوْجَة`,p:`زوجة`,tr:`zawja`,fr:`femme, épouse`,fm:`Nom fém.`,root:`ز و ج`},
      {w:`عَمّ`,p:`عم`,tr:`ʿamm`,fr:`oncle paternel`,fm:`Nom — géminé`,root:`ع م م`},
      {w:`عَمَّة`,p:`عمة`,tr:`ʿamma`,fr:`tante paternelle`,fm:`Nom fém.`,root:`ع م م`},
      {w:`خَال`,p:`خال`,tr:`khāl`,fr:`oncle maternel`,fm:`Nom`,root:`خ ا ل`},
      {w:`خَالَة`,p:`خالة`,tr:`khāla`,fr:`tante maternelle`,fm:`Nom fém.`,root:`خ ا ل`},
      {w:`ابْن عَمّ`,p:`ابن عم`,tr:`ibn ʿamm`,fr:`cousin paternel`,fm:`Idāfa`,root:`ع م م`},
      {w:`بِنْت خَال`,p:`بنت خال`,tr:`bint khāl`,fr:`cousine maternelle`,fm:`Idāfa`,root:`خ ا ل`},
      {w:`حَفِيد`,p:`حفيد`,tr:`ḥafīd`,fr:`petit-fils`,fm:`Nom — schème فَعِيل`,root:`ح ف د`},
      {w:`حَفِيدَة`,p:`حفيدة`,tr:`ḥafīda`,fr:`petite-fille`,fm:`Nom fém.`,root:`ح ف د`},
      {w:`حَمَاة`,p:`حماة`,tr:`ḥamāh`,fr:`belle-mère`,fm:`Nom`,root:`ح م و`},
      {w:`حَمُو`,p:`حمو`,tr:`ḥamū`,fr:`beau-père (mari de la mère)`,fm:`Nom défectueux`,root:`ح م و`},
      {w:`كَنَّة`,p:`كنة`,tr:`kanna`,fr:`belle-fille (femme du fils)`,fm:`Nom`,root:`ك ن ن`},
      {w:`صِهْر`,p:`صهر`,tr:`ṣihr`,fr:`beau-frère, beau-père`,fm:`Nom — schème فِعْل`,root:`ص ه ر`},
      {w:`يَتِيم`,p:`يتيم`,tr:`yatīm`,fr:`orphelin (pl. أَيْتَام)`,fm:`Adjectif substantivé`,root:`ي ت م`},
      {w:`رَضِيع`,p:`رضيع`,tr:`raḍīʿ`,fr:`nourrisson à l'allaitement`,fm:`Nom — schème فَعِيل`,root:`ر ض ع`},
      {w:`مَوْلُود`,p:`مولود`,tr:`mawlūd`,fr:`nouveau-né, bébé`,fm:`Participe passif Form I`,root:`و ل د`},
      {w:`تَوْأَم`,p:`توأم`,tr:`tawʾam`,fr:`jumeau (pl. تَوَائِم)`,fm:`Nom — schème فَوْعَل`,root:`ت و م`},
      {w:`عَائِلَة`,p:`عائلة`,tr:`ʿāʾila`,fr:`famille (terme courant)`,fm:`Participe actif fém. Form I`,root:`ع و ل`},
      {w:`نَسَب`,p:`نسب`,tr:`nasab`,fr:`lignage, généalogie`,fm:`Masdar Form I`,root:`ن س ب`},
      {w:`قَرَابَة`,p:`قرابة`,tr:`qarāba`,fr:`parenté, lien familial`,fm:`Masdar Form I`,root:`ق ر ب`},
      {w:`صِلَة الرَّحِم`,p:`صلة الرحم`,tr:`ṣilat ar-raḥim`,fr:`lien de parenté (concept islamique)`,fm:`Idāfa`,root:`ر ح م`},
      {w:`ذُرِّيَّة`,p:`ذرية`,tr:`dhurriyya`,fr:`descendance, progéniture`,fm:`Nom — géminé`,root:`ذ ر ر`},
      {w:`جِيل`,p:`جيل`,tr:`jīl`,fr:`génération (pl. أَجْيَال)`,fm:`Nom — schème فِعْل`,root:`ج ي ل`},
      {w:`أَرْمَلَة`,p:`أرملة`,tr:`armala`,fr:`veuve`,fm:`Nom — schème أَفْعَلَة`,root:`ر م ل`},
      {w:`أَرْمَل`,p:`أرمل`,tr:`armal`,fr:`veuf`,fm:`Nom — schème أَفْعَل`,root:`ر م ل`},
      {w:`مُطَلَّقَة`,p:`مطلقة`,tr:`muṭallaqa`,fr:`divorcée`,fm:`Participe passif Form II fém.`,root:`ط ل ق`},
      {w:`وَلَد بِكْر`,p:`ولد بكر`,tr:`walad bikr`,fr:`fils aîné, premier-né`,fm:`Syntagme nominal`,root:`ب ك ر`},
      {w:`رُبُّ الأُسْرَة`,p:`رب الأسرة`,tr:`rabb al-usra`,fr:`chef de famille`,fm:`Idāfa`,root:`ر ب ب`},
      {w:`عَزَبٌ`,p:`عزب`,tr:`ʿazab`,fr:`célibataire (m.)`,fm:`Adjectif`,root:`ع ز ب`}
    ]
  },
  {
    theme:`الْجِسْمُ الإِنْسَانِيُّ الْكَامِلُ — Corps humain complet`,
    words:[
      {w:`جَبْهَة`,p:`جبهة`,tr:`jabha`,fr:`front`,fm:`Nom — schème فَعْلَة`,root:`ج ب ه`},
      {w:`خَدّ`,p:`خد`,tr:`khadd`,fr:`joue (pl. خُدُود)`,fm:`Nom — géminé`,root:`خ د د`},
      {w:`ذَقَن`,p:`ذقن`,tr:`dhaqan`,fr:`menton, barbe`,fm:`Nom — schème فَعَل`,root:`ذ ق ن`},
      {w:`رَقَبَة`,p:`رقبة`,tr:`raqaba`,fr:`cou, nuque`,fm:`Nom — schème فَعَلَة`,root:`ر ق ب`},
      {w:`كَتِف`,p:`كتف`,tr:`katif`,fr:`épaule (pl. أَكْتَاف)`,fm:`Nom — schème فَعِل`,root:`ك ت ف`},
      {w:`صَدْر`,p:`صدر`,tr:`ṣadr`,fr:`poitrine, sein`,fm:`Nom — schème فَعْل`,root:`ص د ر`},
      {w:`ظَهْر`,p:`ظهر`,tr:`ẓahr`,fr:`dos (pl. ظُهُور)`,fm:`Nom — schème فَعْل`,root:`ظ ه ر`},
      {w:`بَطْن`,p:`بطن`,tr:`baṭn`,fr:`ventre, abdomen`,fm:`Nom — schème فَعْل`,root:`ب ط ن`},
      {w:`رُكْبَة`,p:`ركبة`,tr:`rukba`,fr:`genou (pl. رُكَب)`,fm:`Nom — schème فُعْلَة`,root:`ر ك ب`},
      {w:`كَاحِل`,p:`كاحل`,tr:`kāḥil`,fr:`cheville`,fm:`Nom — participe Form I`,root:`ك ح ل`},
      {w:`إِبْهَام`,p:`إبهام`,tr:`ibhām`,fr:`pouce`,fm:`Nom — schème إِفْعَال`,root:`ب ه م`},
      {w:`رِئَة`,p:`رئة`,tr:`riʾa`,fr:`poumon (pl. رِئَات)`,fm:`Nom`,root:`ر أ ي`},
      {w:`قَلْب`,p:`قلب`,tr:`qalb`,fr:`cœur (pl. قُلُوب)`,fm:`Nom — schème فَعْل`,root:`ق ل ب`},
      {w:`كَبِد`,p:`كبد`,tr:`kabid`,fr:`foie`,fm:`Nom — schème فَعِل`,root:`ك ب د`},
      {w:`كُلْيَة`,p:`كلية`,tr:`kulya`,fr:`rein (pl. كُلْيَتَانِ/كُلْيَات)`,fm:`Nom`,root:`ك ل ي`},
      {w:`عَظْم`,p:`عظم`,tr:`ʿaẓm`,fr:`os (pl. عِظَام)`,fm:`Nom — schème فَعْل`,root:`ع ظ م`},
      {w:`جِلْد`,p:`جلد`,tr:`jild`,fr:`peau, cuir (pl. جُلُود)`,fm:`Nom — schème فِعْل`,root:`ج ل د`},
      {w:`دَم`,p:`دم`,tr:`dam`,fr:`sang`,fm:`Nom — schème فَعَل`,root:`د م م`},
      {w:`عَصَب`,p:`عصب`,tr:`ʿaṣab`,fr:`nerf (pl. أَعْصَاب)`,fm:`Nom — schème فَعَل`,root:`ع ص ب`},
      {w:`عَضَلَة`,p:`عضلة`,tr:`ʿaḍala`,fr:`muscle (pl. عَضَلَات)`,fm:`Nom — schème فَعَلَة`,root:`ع ض ل`},
      {w:`لِسَان`,p:`لسان`,tr:`lisān`,fr:`langue (organe) (pl. أَلْسِنَة)`,fm:`Nom — schème فِعَال`,root:`ل س ن`},
      {w:`شَعَر`,p:`شعر`,tr:`shaʿar`,fr:`cheveux (collectif)`,fm:`Nom collectif`,root:`ش ع ر`},
      {w:`لِحْيَة`,p:`لحية`,tr:`liḥya`,fr:`barbe`,fm:`Nom — schème فِعْلَة`,root:`ل ح ي`},
      {w:`شَفَة`,p:`شفة`,tr:`shafa`,fr:`lèvre (pl. شِفَاه)`,fm:`Nom — défectueux`,root:`ش ف ه`},
      {w:`حَاجِب`,p:`حاجب`,tr:`ḥājib`,fr:`sourcil (pl. حَوَاجِب)`,fm:`Participe actif Form I`,root:`ح ج ب`},
      {w:`رِمْش`,p:`رمش`,tr:`rimsh`,fr:`cil (pl. رُمُوش)`,fm:`Nom — schème فِعْل`,root:`ر م ش`},
      {w:`وَرِيد`,p:`وريد`,tr:`warīd`,fr:`veine (pl. أَوْرِدَة)`,fm:`Nom — schème فَعِيل`,root:`و ر د`},
      {w:`شَرْيَان`,p:`شريان`,tr:`sharyān`,fr:`artère (pl. شَرَايِين)`,fm:`Nom`,root:`ش ر ي`},
      {w:`دِمَاغ`,p:`دماغ`,tr:`dimāgh`,fr:`cerveau`,fm:`Nom — schème فِعَال`,root:`د م غ`},
      {w:`عَمُود الْفَقَرِيّ`,p:`عمود فقري`,tr:`ʿamūd faqarī`,fr:`colonne vertébrale`,fm:`Idāfa + nisba`,root:`ف ق ر`},
      {w:`كُوع`,p:`كوع`,tr:`kūʿ`,fr:`coude`,fm:`Nom — schème فُعْل`,root:`ك و ع`},
      {w:`مَعِدَة`,p:`معدة`,tr:`maʿida`,fr:`estomac`,fm:`Nom — schème مَفْعِلَة`,root:`ع م د`},
      {w:`حَلْق`,p:`حلق`,tr:`ḥalq`,fr:`gorge, gosier`,fm:`Nom — schème فَعْل`,root:`ح ل ق`},
      {w:`أُصْبُع`,p:`أصبع`,tr:`uṣbuʿ`,fr:`doigt (pl. أَصَابِع)`,fm:`Nom — schème أُفْعُل`,root:`ص ب ع`},
      {w:`كَفّ`,p:`كف`,tr:`kaff`,fr:`paume de la main (pl. كُفُوف)`,fm:`Nom — géminé`,root:`ك ف ف`}
    ]
  },
  {
    theme:`الأَغْذِيَةُ وَالْمَطْبَخُ — Alimentation et cuisine`,
    words:[
      {w:`قَمْح`,p:`قمح`,tr:`qamḥ`,fr:`blé`,fm:`Nom collectif`,root:`ق م ح`},
      {w:`دَقِيق`,p:`دقيق`,tr:`daqīq`,fr:`farine`,fm:`Nom — schème فَعِيل`,root:`د ق ق`},
      {w:`سُكَّر`,p:`سكر`,tr:`sukkar`,fr:`sucre`,fm:`Nom (emprunt)`,root:`س ك ر`},
      {w:`مِلْح`,p:`ملح`,tr:`milḥ`,fr:`sel`,fm:`Nom — schème فِعْل`,root:`م ل ح`},
      {w:`زَيْت`,p:`زيت`,tr:`zayt`,fr:`huile, olive`,fm:`Nom — schème فَيْعَل`,root:`ز ي ت`},
      {w:`خَلّ`,p:`خل`,tr:`khall`,fr:`vinaigre`,fm:`Nom — géminé`,root:`خ ل ل`},
      {w:`فِلْفِل`,p:`فلفل`,tr:`fulfil`,fr:`poivre, piment`,fm:`Nom (quadrilitère)`,root:`ف ل ف`},
      {w:`كَرَوِيَّا`,p:`كراويا`,tr:`karawiyyā`,fr:`carvi, cumin`,fm:`Nom (emprunt)`,root:`ك ر و`},
      {w:`زَعْتَر`,p:`زعتر`,tr:`zaʿtar`,fr:`thym, zaatar`,fm:`Nom`,root:`ز ع ت`},
      {w:`قِرْفَة`,p:`قرفة`,tr:`qirfa`,fr:`cannelle`,fm:`Nom — schème فِعْلَة`,root:`ق ر ف`},
      {w:`بَيْضَة`,p:`بيضة`,tr:`bayḍa`,fr:`œuf (pl. بَيْض)`,fm:`Nom — schème فَيْعَلَة`,root:`ب ي ض`},
      {w:`حَلِيب`,p:`حليب`,tr:`ḥalīb`,fr:`lait`,fm:`Nom — schème فَعِيل`,root:`ح ل ب`},
      {w:`زَبَادِيّ`,p:`زبادي`,tr:`zabādī`,fr:`yaourt`,fm:`Nom (emprunt)`,root:`ز ب د`},
      {w:`جَبْنَة`,p:`جبنة`,tr:`jabna`,fr:`fromage (variante fém.)`,fm:`Nom — schème فَعْلَة`,root:`ج ب ن`},
      {w:`عَسَل`,p:`عسل`,tr:`ʿasal`,fr:`miel`,fm:`Nom — schème فَعَل`,root:`ع س ل`},
      {w:`تَمْر`,p:`تمر`,tr:`tamr`,fr:`dattes (collectif)`,fm:`Nom collectif`,root:`ت م ر`},
      {w:`تِين`,p:`تين`,tr:`tīn`,fr:`figues (collectif)`,fm:`Nom collectif`,root:`ت ي ن`},
      {w:`رُمَّان`,p:`رمان`,tr:`rummān`,fr:`grenade (collectif)`,fm:`Nom collectif géminé`,root:`ر م م`},
      {w:`جَوْز`,p:`جوز`,tr:`jawz`,fr:`noix (collectif)`,fm:`Nom collectif`,root:`ج و ز`},
      {w:`لَوْز`,p:`لوز`,tr:`lawz`,fr:`amandes (collectif)`,fm:`Nom collectif`,root:`ل و ز`},
      {w:`حِمَّص`,p:`حمص`,tr:`ḥimmaṣ`,fr:`pois chiches, houmous`,fm:`Nom — géminé`,root:`ح م ص`},
      {w:`طَحِينَة`,p:`طحينة`,tr:`ṭaḥīna`,fr:`tahini (pâte de sésame)`,fm:`Nom — schème فَعِيلَة`,root:`ط ح ن`},
      {w:`فُولٌ`,p:`فول`,tr:`fūl`,fr:`fève, ful medammes`,fm:`Nom`,root:`ف و ل`},
      {w:`بَاذِنْجَان`,p:`باذنجان`,tr:`bādhinjān`,fr:`aubergine (collectif)`,fm:`Nom (emprunt persan)`,root:`—`},
      {w:`كُوسَة`,p:`كوسة`,tr:`kūsa`,fr:`courgette`,fm:`Nom (emprunt)`,root:`—`},
      {w:`فَلْفَل`,p:`فلفل`,tr:`falful`,fr:`poivron`,fm:`Nom (quadrilitère)`,root:`ف ل ف`},
      {w:`طَمَاطِم`,p:`طماطم`,tr:`ṭamāṭim`,fr:`tomates (collectif)`,fm:`Nom (emprunt espagnol)`,root:`—`},
      {w:`بَقْدُونُس`,p:`بقدونس`,tr:`baqdūnus`,fr:`persil`,fm:`Nom (emprunt grec)`,root:`—`},
      {w:`كُزْبَرَة`,p:`كزبرة`,tr:`kuzbara`,fr:`coriandre`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مَرَق`,p:`مرق`,tr:`maraq`,fr:`bouillon, jus de viande`,fm:`Nom — schème فَعَل`,root:`م ر ق`},
      {w:`شَوَاء`,p:`شواء`,tr:`shawāʾ`,fr:`grillade, barbecue`,fm:`Masdar Form I`,root:`ش و ي`},
      {w:`طَجِين`,p:`طجين`,tr:`ṭajīn`,fr:`tajine (plat)`,fm:`Nom (berbère)`,root:`ط ج ن`},
      {w:`كُسْكُسَاء`,p:`كسكساء`,tr:`kuskusāʾ`,fr:`couscous`,fm:`Nom (berbère)`,root:`—`},
      {w:`خُبْزُ الرَّقَاقِ`,p:`خبز الرقاق`,tr:`khubz ar-raqāq`,fr:`pain mince, galette`,fm:`Idāfa`,root:`ر ق ق`},
      {w:`قَهْوَة تُرْكِيَّة`,p:`قهوة تركية`,tr:`qahwa turkiyya`,fr:`café turc`,fm:`Syntagme`,root:`ق ه و`},
      {w:`عَصِير`,p:`عصير`,tr:`ʿaṣīr`,fr:`jus de fruits`,fm:`Nom — schème فَعِيل`,root:`ع ص ر`},
      {w:`حِسَاء`,p:`حساء`,tr:`ḥisāʾ`,fr:`soupe, bouillon`,fm:`Nom — schème فِعَال`,root:`ح س و`},
      {w:`وَجْبَة`,p:`وجبة`,tr:`wajba`,fr:`repas, plat (pl. وَجَبَات)`,fm:`Nom — schème فَعْلَة`,root:`و ج ب`},
      {w:`شَهِيَّة`,p:`شهية`,tr:`shahiyya`,fr:`appétit, envie de manger`,fm:`Nom — schème فَعِيلَة`,root:`ش ه و`},
      {w:`طَاهٍ`,p:`طاهٍ`,tr:`ṭāhin`,fr:`cuisinier, chef`,fm:`Participe actif Form I — défectueux`,root:`ط ه و`},
      {w:`طَبَخَ`,p:`طبخ`,tr:`ṭabakha`,fr:`cuisiner, cuire`,fm:`Verbe Form I`,root:`ط ب خ`},
      {w:`شَوَى`,p:`شوى`,tr:`shawā`,fr:`griller, rôtir`,fm:`Verbe Form I — défectueux`,root:`ش و ي`},
      {w:`قَلَى`,p:`قلى`,tr:`qalā`,fr:`frire`,fm:`Verbe Form I — défectueux`,root:`ق ل ي`},
      {w:`سَلَقَ`,p:`سلق`,tr:`salaqa`,fr:`bouillir, ébouillanter`,fm:`Verbe Form I`,root:`س ل ق`},
      {w:`حَمَصَ`,p:`حمص`,tr:`ḥamaṣa`,fr:`torréfier, griller à sec`,fm:`Verbe Form I`,root:`ح م ص`}
    ]
  },
  {
    theme:`الْمَنْزِلُ وَالأَثَاثُ — Maison et mobilier`,
    words:[
      {w:`شُبَّاك`,p:`شباك`,tr:`shubbāk`,fr:`fenêtre (autre terme, pl. شَبَابِيك)`,fm:`Nom — géminé`,root:`ش ب ك`},
      {w:`بَاب`,p:`باب`,tr:`bāb`,fr:`porte, portail (pl. أَبْوَاب)`,fm:`Nom — schème فَعْل`,root:`ب و ب`},
      {w:`دَرَج`,p:`درج`,tr:`daraj`,fr:`escalier (pl. دَرَجَات)`,fm:`Nom — schème فَعَل`,root:`د ر ج`},
      {w:`سَقْف`,p:`سقف`,tr:`saqf`,fr:`plafond, toit (pl. سُقُوف)`,fm:`Nom — schème فَعْل`,root:`س ق ف`},
      {w:`أَرْضِيَّة`,p:`أرضية`,tr:`arḍiyya`,fr:`sol, plancher`,fm:`Nisba de أَرْض`,root:`أ ر ض`},
      {w:`جِدَار`,p:`جدار`,tr:`jidār`,fr:`mur, paroi (pl. جُدْران)`,fm:`Nom — schème فِعَال`,root:`ج د ر`},
      {w:`رِوَاق`,p:`رواق`,tr:`riwāq`,fr:`couloir, corridor`,fm:`Nom — schème فِعَال`,root:`ر و ق`},
      {w:`شُرْفَة`,p:`شرفة`,tr:`shurfa`,fr:`balcon, terrasse`,fm:`Nom — schème فُعْلَة`,root:`ش ر ف`},
      {w:`قَبُو`,p:`قبو`,tr:`qabū`,fr:`cave, sous-sol`,fm:`Nom`,root:`ق ب و`},
      {w:`مِصْعَد`,p:`مصعد`,tr:`miṣʿad`,fr:`ascenseur`,fm:`Nom de lieu Form I`,root:`ص ع د`},
      {w:`صُنْبُور`,p:`صنبور`,tr:`ṣunbūr`,fr:`robinet`,fm:`Nom`,root:`ص ن ب`},
      {w:`حَوْض`,p:`حوض`,tr:`ḥawḍ`,fr:`évier, bassine (pl. أَحْوَاض)`,fm:`Nom — schème فَعْل`,root:`ح و ض`},
      {w:`بَالُوعَة`,p:`بالوعة`,tr:`bālūʿa`,fr:`siphon, égout`,fm:`Nom`,root:`ب ل ع`},
      {w:`سَخَّانَة`,p:`سخانة`,tr:`sakhkhāna`,fr:`chauffe-eau`,fm:`Nom — schème فَعَّالَة`,root:`س خ ن`},
      {w:`مَكْيِّف`,p:`مكيف`,tr:`mukayyif`,fr:`climatiseur`,fm:`Participe actif Form II`,root:`ك ي ف`},
      {w:`مِرْوَحَة`,p:`مروحة`,tr:`mirwaḥa`,fr:`ventilateur`,fm:`Nom — schème مِفْعَلَة`,root:`ر و ح`},
      {w:`إِضَاءَة`,p:`إضاءة`,tr:`iḍāʾa`,fr:`éclairage`,fm:`Masdar Form IV`,root:`ض و أ`},
      {w:`مُفْتَاح`,p:`مفتاح`,tr:`miftāḥ`,fr:`clé (pl. مَفَاتِيح)`,fm:`Nom — schème مِفْعَال`,root:`ف ت ح`},
      {w:`قُفْل`,p:`قفل`,tr:`qufl`,fr:`serrure, verrou`,fm:`Nom — schème فُعْل`,root:`ق ف ل`},
      {w:`سِجَّادَة`,p:`سجادة`,tr:`sajjāda`,fr:`tapis de prière, carpette`,fm:`Nom — géminé`,root:`س ج د`},
      {w:`سَتَائِر`,p:`ستائر`,tr:`satāʾir`,fr:`rideaux (pl. de سِتَارَة)`,fm:`Pl. brisé`,root:`س ت ر`},
      {w:`رَفّ`,p:`رف`,tr:`raff`,fr:`étagère, planche`,fm:`Nom — géminé`,root:`ر ف ف`},
      {w:`دَوْلَاب`,p:`دولاب`,tr:`dawlāb`,fr:`armoire (dialecte)`,fm:`Nom (emprunt)`,root:`د و ل`},
      {w:`صِيوَان`,p:`صيوان`,tr:`ṣiwān`,fr:`auvent, marquise`,fm:`Nom`,root:`ص و ن`},
      {w:`مَسْبَح`,p:`مسبح`,tr:`masbaḥ`,fr:`piscine`,fm:`Nom de lieu Form I`,root:`س ب ح`},
      {w:`غَرَاج`,p:`غراج`,tr:`garāj`,fr:`garage`,fm:`Nom (emprunt français)`,root:`—`},
      {w:`حَظِيرَة`,p:`حظيرة`,tr:`ḥaẓīra`,fr:`cour, enclos`,fm:`Nom — schème فَعِيلَة`,root:`ح ظ ر`},
      {w:`بِئْر`,p:`بئر`,tr:`biʾr`,fr:`puits`,fm:`Nom fém. — schème فِعْل`,root:`ب أ ر`},
      {w:`خَزَّان`,p:`خزان`,tr:`khazzān`,fr:`réservoir, citerne`,fm:`Nom — schème فَعَّال`,root:`خ ز ن`},
      {w:`سُلَّم`,p:`سلم`,tr:`sullam`,fr:`escalier, échelle (pl. سَلَالِم)`,fm:`Nom — géminé`,root:`س ل م`}
    ]
  },
  {
    theme:`الطَّبِيعَةُ وَالْمَنَاخُ — Nature et climat`,
    words:[
      {w:`وَادٍ`,p:`وادٍ`,tr:`wādin`,fr:`vallée, oued (pl. أَوْدِيَة)`,fm:`Nom défectueux`,root:`و د ي`},
      {w:`جَبَل`,p:`جبل`,tr:`jabal`,fr:`montagne (pl. جِبَال)`,fm:`Nom — schème فَعَل`,root:`ج ب ل`},
      {w:`هَضْبَة`,p:`هضبة`,tr:`haḍba`,fr:`plateau, haut plateau`,fm:`Nom — schème فَعْلَة`,root:`ه ض ب`},
      {w:`سَهْل`,p:`سهل`,tr:`sahl`,fr:`plaine, prairie`,fm:`Nom — schème فَعْل`,root:`س ه ل`},
      {w:`نَهْر`,p:`نهر`,tr:`nahr`,fr:`fleuve, rivière (pl. أَنْهَار)`,fm:`Nom — schème فَعْل`,root:`ن ه ر`},
      {w:`بُحَيْرَة`,p:`بحيرة`,tr:`buḥayra`,fr:`lac`,fm:`Nom — diminutif de بَحْر`,root:`ب ح ر`},
      {w:`مُحِيط`,p:`محيط`,tr:`muḥīṭ`,fr:`océan (pl. مُحِيطَات)`,fm:`Participe actif Form IV`,root:`ح و ط`},
      {w:`شَلَّال`,p:`شلال`,tr:`shallāl`,fr:`cascade, chute d'eau`,fm:`Nom — géminé`,root:`ش ل ل`},
      {w:`نَبْع`,p:`نبع`,tr:`nabʿ`,fr:`source (pl. يَنَابِيع)`,fm:`Masdar Form I`,root:`ن ب ع`},
      {w:`خَلِيج`,p:`خليج`,tr:`khalīj`,fr:`golfe, détroit`,fm:`Nom — schème فَعِيل`,root:`خ ل ج`},
      {w:`جَزِيرَة`,p:`جزيرة`,tr:`jazīra`,fr:`île (pl. جُزُر)`,fm:`Nom — schème فَعِيلَة`,root:`ج ز ر`},
      {w:`شِبْهُ جَزِيرَة`,p:`شبه جزيرة`,tr:`shibh jazīra`,fr:`péninsule`,fm:`Idāfa`,root:`ج ز ر`},
      {w:`صَخْرَة`,p:`صخرة`,tr:`ṣakhra`,fr:`rocher, roche`,fm:`Nom — schème فَعْلَة`,root:`ص خ ر`},
      {w:`تُرْبَة`,p:`تربة`,tr:`turba`,fr:`terre, sol, terreau`,fm:`Nom — schème فُعْلَة`,root:`ت ر ب`},
      {w:`رَمْل`,p:`رمل`,tr:`raml`,fr:`sable (collectif pl. رِمَال)`,fm:`Nom collectif`,root:`ر م ل`},
      {w:`طِين`,p:`طين`,tr:`ṭīn`,fr:`argile, boue`,fm:`Nom — schème فِعْل`,root:`ط ي ن`},
      {w:`سَحَابَة`,p:`سحابة`,tr:`saḥāba`,fr:`nuage (pl. سَحَاب)`,fm:`Nom — schème فَعَالَة`,root:`س ح ب`},
      {w:`بَرْق`,p:`برق`,tr:`barq`,fr:`éclair (pl. بُرُوق)`,fm:`Nom — schème فَعْل`,root:`ب ر ق`},
      {w:`رَعْد`,p:`رعد`,tr:`raʿd`,fr:`tonnerre`,fm:`Nom — schème فَعْل`,root:`ر ع د`},
      {w:`ضَبَاب`,p:`ضباب`,tr:`ḍabāb`,fr:`brouillard`,fm:`Nom — schème فَعَال`,root:`ض ب ب`},
      {w:`نَسِيم`,p:`نسيم`,tr:`nasīm`,fr:`brise, zéphyr`,fm:`Nom — schème فَعِيل`,root:`ن س م`},
      {w:`رِيح`,p:`ريح`,tr:`rīḥ`,fr:`vent (pl. رِيَاح / أَرْيَاح)`,fm:`Nom fém. — schème فِعْل`,root:`ر ي ح`},
      {w:`عَاصِفَة`,p:`عاصفة`,tr:`ʿāṣifa`,fr:`tempête, ouragan`,fm:`Participe actif fém.`,root:`ع ص ف`},
      {w:`فَيَضَان`,p:`فيضان`,tr:`fayaḍān`,fr:`inondation, crue`,fm:`Masdar Form I`,root:`ف ي ض`},
      {w:`جَفَاف`,p:`جفاف`,tr:`jafāf`,fr:`sécheresse`,fm:`Masdar Form I`,root:`ج ف ف`},
      {w:`تَرْبِيَة`,p:`تربة`,tr:`turba`,fr:`sol fertile, terreau`,fm:`Nom`,root:`ت ر ب`},
      {w:`شَجَرَة`,p:`شجرة`,tr:`shajara`,fr:`arbre (pl. أَشْجَار)`,fm:`Nom — schème فَعَلَة`,root:`ش ج ر`},
      {w:`عُشْب`,p:`عشب`,tr:`ʿushb`,fr:`herbe, gazon`,fm:`Nom collectif`,root:`ع ش ب`},
      {w:`نَبَات`,p:`نبات`,tr:`nabāt`,fr:`plante, végétation`,fm:`Masdar Form I`,root:`ن ب ت`},
      {w:`وَرْد`,p:`ورد`,tr:`ward`,fr:`roses (collectif)`,fm:`Nom collectif`,root:`و ر د`},
      {w:`شَوْك`,p:`شوك`,tr:`shawk`,fr:`épines (collectif)`,fm:`Nom collectif`,root:`ش و ك`},
      {w:`جَوْهَرَة`,p:`جوهرة`,tr:`jawhara`,fr:`gemme, joyau`,fm:`Nom — quadrilitère`,root:`ج و ه`},
      {w:`مَعْدِن`,p:`معدن`,tr:`maʿdin`,fr:`métal, minéral (pl. مَعَادِن)`,fm:`Nom de lieu Form I`,root:`ع د ن`},
      {w:`ذَهَب`,p:`ذهب`,tr:`dhahab`,fr:`or`,fm:`Nom — schème فَعَل`,root:`ذ ه ب`},
      {w:`فِضَّة`,p:`فضة`,tr:`fiḍḍa`,fr:`argent (métal)`,fm:`Nom — géminé`,root:`ف ض ض`}
    ]
  },
  {
    theme:`الْحَيَوَانَاتُ وَالطُّيُورُ — Animaux et oiseaux`,
    words:[
      {w:`ثَعْلَب`,p:`ثعلب`,tr:`thaʿlab`,fr:`renard (pl. ثَعَالِب)`,fm:`Nom — schème فَعْلَل`,root:`ث ع ل`},
      {w:`ذِئْب`,p:`ذئب`,tr:`dhiʾb`,fr:`loup (pl. ذِئَاب)`,fm:`Nom — schème فِعْل`,root:`ذ أ ب`},
      {w:`ضَبُع`,p:`ضبع`,tr:`ḍabuʿ`,fr:`hyène`,fm:`Nom — schème فَعُل`,root:`ض ب ع`},
      {w:`فَهْد`,p:`فهد`,tr:`fahd`,fr:`guépard, léopard`,fm:`Nom — schème فَعْل`,root:`ف ه د`},
      {w:`نَمِر`,p:`نمر`,tr:`namir`,fr:`tigre, panthère`,fm:`Nom — schème فَعِل`,root:`ن م ر`},
      {w:`فِيل`,p:`فيل`,tr:`fīl`,fr:`éléphant (pl. فِيَلَة)`,fm:`Nom — schème فِعْل`,root:`ف ي ل`},
      {w:`زَرَافَة`,p:`زرافة`,tr:`zarāfa`,fr:`girafe`,fm:`Nom`,root:`ز ر ف`},
      {w:`حِمَار`,p:`حمار`,tr:`ḥimār`,fr:`âne (pl. حَمِير)`,fm:`Nom — schème فِعَال`,root:`ح م ر`},
      {w:`بَغْل`,p:`بغل`,tr:`baghl`,fr:`mulet`,fm:`Nom — schème فَعْل`,root:`ب غ ل`},
      {w:`بَقَرَة`,p:`بقرة`,tr:`baqara`,fr:`vache (pl. بَقَر)`,fm:`Nom — schème فَعَلَة`,root:`ب ق ر`},
      {w:`خَرُوف`,p:`خروف`,tr:`kharūf`,fr:`mouton (pl. خِرَاف)`,fm:`Nom — schème فَعُول`,root:`خ ر ف`},
      {w:`مَاعِز`,p:`ماعز`,tr:`māʿiz`,fr:`chèvre`,fm:`Participe actif Form I`,root:`م ع ز`},
      {w:`ثَوْر`,p:`ثور`,tr:`thawr`,fr:`taureau, bœuf (pl. ثِيرَان)`,fm:`Nom — schème فَعْل`,root:`ث و ر`},
      {w:`حِصَان`,p:`حصان`,tr:`ḥiṣān`,fr:`cheval (pl. أَحْصِنَة)`,fm:`Nom — schème فِعَال`,root:`ح ص ن`},
      {w:`جَمَل`,p:`جمل`,tr:`jamal`,fr:`chameau (pl. جِمَال)`,fm:`Nom — schème فَعَل`,root:`ج م ل`},
      {w:`نَاقَة`,p:`ناقة`,tr:`nāqa`,fr:`chamelle`,fm:`Nom — schème فَاعِلَة`,root:`ن و ق`},
      {w:`قِرْد`,p:`قرد`,tr:`qird`,fr:`singe (pl. قِرَدَة)`,fm:`Nom — schème فِعْل`,root:`ق ر د`},
      {w:`أَرْنَب`,p:`أرنب`,tr:`arnab`,fr:`lapin (pl. أَرَانِب)`,fm:`Nom — schème أَفْعَل`,root:`أ ر ن`},
      {w:`قُنْفُذ`,p:`قنفذ`,tr:`qunfudh`,fr:`hérisson`,fm:`Nom — schème فُعْلُل`,root:`ق ن ف`},
      {w:`ثُعْبَان`,p:`ثعبان`,tr:`thuʿbān`,fr:`serpent (pl. ثَعَابِين)`,fm:`Nom — schème فُعْلَان`,root:`ث ع ب`},
      {w:`تِمْسَاح`,p:`تمساح`,tr:`timsāḥ`,fr:`crocodile`,fm:`Nom`,root:`ت م س`},
      {w:`سُلَحْفَاة`,p:`سلحفاة`,tr:`sulḥafāh`,fr:`tortue`,fm:`Nom`,root:`س ل ح`},
      {w:`ضِفْدَع`,p:`ضفدع`,tr:`ḍifdiʿ`,fr:`grenouille`,fm:`Nom — schème فِعْلَل`,root:`ض ف د`},
      {w:`عَقْرَب`,p:`عقرب`,tr:`ʿaqrab`,fr:`scorpion`,fm:`Nom — schème فَعْلَل`,root:`ع ق ر`},
      {w:`نَمْل`,p:`نمل`,tr:`naml`,fr:`fourmis (collectif)`,fm:`Nom collectif`,root:`ن م ل`},
      {w:`نَحْل`,p:`نحل`,tr:`naḥl`,fr:`abeilles (collectif)`,fm:`Nom collectif`,root:`ن ح ل`},
      {w:`فَرَاشَة`,p:`فراشة`,tr:`farāsha`,fr:`papillon`,fm:`Nom — schème فَعَالَة`,root:`ف ر ش`},
      {w:`نَسْر`,p:`نسر`,tr:`nasr`,fr:`vautour, aigle (pl. نُسُور)`,fm:`Nom — schème فَعْل`,root:`ن س ر`},
      {w:`صَقْر`,p:`صقر`,tr:`ṣaqr`,fr:`faucon (pl. صُقُور)`,fm:`Nom — schème فَعْل`,root:`ص ق ر`},
      {w:`بُومَة`,p:`بومة`,tr:`būma`,fr:`hibou, chouette`,fm:`Nom — schème فُعْلَة`,root:`ب و م`},
      {w:`غُرَاب`,p:`غراب`,tr:`ghurāb`,fr:`corbeau (pl. غِرْبَان)`,fm:`Nom — schème فُعَال`,root:`غ ر ب`},
      {w:`حَمَامَة`,p:`حمامة`,tr:`ḥamāma`,fr:`pigeon, colombe`,fm:`Nom — schème فَعَالَة`,root:`ح م م`},
      {w:`بَبَّغَاء`,p:`ببغاء`,tr:`babbghāʾ`,fr:`perroquet`,fm:`Nom — géminé`,root:`ب ب غ`},
      {w:`حُوت`,p:`حوت`,tr:`ḥūt`,fr:`baleine, gros poisson`,fm:`Nom — schème فُعْل`,root:`ح و ت`},
      {w:`سَمَكَة`,p:`سمكة`,tr:`samaka`,fr:`poisson (pl. أَسْمَاك)`,fm:`Nom — schème فَعَلَة`,root:`س م ك`},
      {w:`دُولْفِين`,p:`دولفين`,tr:`dulfīn`,fr:`dauphin`,fm:`Nom (emprunt)`,root:`—`},
      {w:`حَشَرَة`,p:`حشرة`,tr:`ḥashara`,fr:`insecte (pl. حَشَرَات)`,fm:`Nom — schème فَعَلَة`,root:`ح ش ر`}
    ]
  },
  {
    theme:`الدِّينُ وَالْعِبَادَةُ — مُبْتَدِئ — Religion et adoration (débutant)`,
    words:[
      {w:`اللهُ`,p:`الله`,tr:`Allāh`,fr:`Allah — Dieu (islam)`,fm:`Nom propre divin`,root:`أ ل ه`},
      {w:`إِسْلَام`,p:`إسلام`,tr:`islām`,fr:`islam (soumission à Dieu)`,fm:`Masdar Form IV`,root:`س ل م`},
      {w:`مُسْلِم`,p:`مسلم`,tr:`muslim`,fr:`musulman (pl. مُسْلِمُون)`,fm:`Participe actif Form IV`,root:`س ل م`},
      {w:`إِيمَان`,p:`إيمان`,tr:`īmān`,fr:`foi, croyance`,fm:`Masdar Form IV`,root:`أ م ن`},
      {w:`مُؤْمِن`,p:`مؤمن`,tr:`muʾmin`,fr:`croyant (pl. مُؤْمِنُون)`,fm:`Participe actif Form IV`,root:`أ م ن`},
      {w:`قُرْآن`,p:`قرآن`,tr:`qurʾān`,fr:`Coran`,fm:`Masdar Form I`,root:`ق ر أ`},
      {w:`سُورَة`,p:`سورة`,tr:`sūra`,fr:`sourate (pl. سُوَر)`,fm:`Nom — schème فُعْلَة`,root:`س و ر`},
      {w:`آيَة`,p:`آية`,tr:`āya`,fr:`verset coranique, signe`,fm:`Nom défectueux`,root:`أ ي ي`},
      {w:`حَدِيث`,p:`حديث`,tr:`ḥadīth`,fr:`hadith, parole du Prophète`,fm:`Nom — schème فَعِيل`,root:`ح د ث`},
      {w:`نَبِيّ`,p:`نبي`,tr:`nabī`,fr:`prophète (pl. أَنْبِيَاء)`,fm:`Nom — schème فَعِيل`,root:`ن ب أ`},
      {w:`رَسُول`,p:`رسول`,tr:`rasūl`,fr:`messager, prophète`,fm:`Nom — schème فَعُول`,root:`ر س ل`},
      {w:`مَلَك`,p:`ملك`,tr:`malak`,fr:`ange (pl. مَلَائِكَة)`,fm:`Nom — schème فَعَل`,root:`م ل ك`},
      {w:`جِبْرِيل`,p:`جبريل`,tr:`jibrīl`,fr:`Gabriel (archange)`,fm:`Nom propre`,root:`—`},
      {w:`صَلَاة`,p:`صلاة`,tr:`ṣalāh`,fr:`prière (pl. صَلَوَات)`,fm:`Nom défectueux`,root:`ص ل و`},
      {w:`صِيَام`,p:`صيام`,tr:`ṣiyām`,fr:`jeûne`,fm:`Masdar Form I`,root:`ص و م`},
      {w:`زَكَاة`,p:`زكاة`,tr:`zakāh`,fr:`zakat, aumône légale`,fm:`Nom défectueux`,root:`ز ك و`},
      {w:`حَجّ`,p:`حج`,tr:`ḥajj`,fr:`pèlerinage à La Mecque`,fm:`Masdar Form I — géminé`,root:`ح ج ج`},
      {w:`أَذَان`,p:`أذان`,tr:`adhān`,fr:`appel à la prière`,fm:`Masdar Form IV`,root:`أ ذ ن`},
      {w:`وُضُوء`,p:`وضوء`,tr:`wuḍūʾ`,fr:`ablutions rituelles`,fm:`Masdar Form I`,root:`و ض أ`},
      {w:`قِبْلَة`,p:`قبلة`,tr:`qibla`,fr:`direction de La Mecque`,fm:`Nom — schème فِعْلَة`,root:`ق ب ل`},
      {w:`جُمُعَة`,p:`جمعة`,tr:`jumuʿa`,fr:`vendredi, prière du vendredi`,fm:`Nom — schème فُعُلَة`,root:`ج م ع`},
      {w:`رَمَضَان`,p:`رمضان`,tr:`ramaḍān`,fr:`Ramadan (9e mois lunaire)`,fm:`Nom propre — géminé`,root:`ر م ض`},
      {w:`عِيد الْفِطْر`,p:`عيد الفطر`,tr:`ʿīd al-fiṭr`,fr:`Aïd Al-Fitr`,fm:`Idāfa`,root:`ف ط ر`},
      {w:`عِيد الأَضْحَى`,p:`عيد الأضحى`,tr:`ʿīd al-aḍḥā`,fr:`Aïd Al-Adha`,fm:`Idāfa`,root:`ض ح و`},
      {w:`بِسْمِ اللهِ`,p:`بسم الله`,tr:`bismillāh`,fr:`au nom de Dieu (basmala)`,fm:`Expression figée`,root:`س م و`},
      {w:`الْحَمْدُ لِلَّهِ`,p:`الحمد لله`,tr:`al-ḥamdulillāh`,fr:`louange à Dieu`,fm:`Expression figée`,root:`ح م د`},
      {w:`سُبْحَانَ اللهِ`,p:`سبحان الله`,tr:`subḥānallāh`,fr:`gloire à Dieu`,fm:`Expression figée`,root:`س ب ح`},
      {w:`اللهُ أَكْبَر`,p:`الله أكبر`,tr:`allāhu akbar`,fr:`Dieu est le plus grand`,fm:`Expression figée`,root:`ك ب ر`},
      {w:`إِنْ شَاءَ اللهُ`,p:`إن شاء الله`,tr:`in shāʾallāh`,fr:`si Dieu le veut`,fm:`Expression figée`,root:`ش ي أ`},
      {w:`مَاشَاءَ اللهُ`,p:`ماشاء الله`,tr:`māshāʾallāh`,fr:`comme Dieu a voulu (admiration)`,fm:`Expression figée`,root:`ش ي أ`}
    ]
  },
  {
    theme:`الصِّفَاتُ وَالْمَشَاعِرُ — Qualités et émotions`,
    words:[
      {w:`سَعِيد`,p:`سعيد`,tr:`saʿīd`,fr:`heureux, content (déjà en A1 textes — rappel)`,fm:`Adj — فَعِيل`,root:`س ع د`},
      {w:`فَرِح`,p:`فرح`,tr:`fariḥ`,fr:`joyeux, gai`,fm:`Adj — schème فَعِل`,root:`ف ر ح`},
      {w:`حَزِين`,p:`حزين`,tr:`ḥazīn`,fr:`triste, malheureux`,fm:`Adj — schème فَعِيل`,root:`ح ز ن`},
      {w:`غَاضِب`,p:`غاضب`,tr:`ghāḍib`,fr:`en colère, fâché`,fm:`Participe actif Form I`,root:`غ ض ب`},
      {w:`خَائِف`,p:`خائف`,tr:`khāʾif`,fr:`effrayé, craintif`,fm:`Participe actif Form I`,root:`خ و ف`},
      {w:`خَجِل`,p:`خجل`,tr:`khajil`,fr:`honteux, timide`,fm:`Adj — schème فَعِل`,root:`خ ج ل`},
      {w:`قَلِق`,p:`قلق`,tr:`qaliq`,fr:`anxieux, inquiet`,fm:`Adj — schème فَعِل`,root:`ق ل ق`},
      {w:`مُرْتَاح`,p:`مرتاح`,tr:`murtāḥ`,fr:`à l'aise, détendu`,fm:`Participe actif Form VIII`,root:`ر و ح`},
      {w:`مَلُول`,p:`ملول`,tr:`malūl`,fr:`ennuyé, las`,fm:`Adj — schème فَعُول`,root:`م ل ل`},
      {w:`مُتَحَمِّس`,p:`متحمس`,tr:`mutaḥammis`,fr:`enthousiaste, passionné`,fm:`Participe actif Form V`,root:`ح م س`},
      {w:`جَرِيء`,p:`جريء`,tr:`jarīʾ`,fr:`courageux, audacieux`,fm:`Adj — schème فَعِيل`,root:`ج ر أ`},
      {w:`جَبَان`,p:`جبان`,tr:`jabān`,fr:`lâche, peureux`,fm:`Adj — schème فَعَال`,root:`ج ب ن`},
      {w:`كَرِيم`,p:`كريم`,tr:`karīm`,fr:`généreux, noble`,fm:`Adj — schème فَعِيل`,root:`ك ر م`},
      {w:`بَخِيل`,p:`بخيل`,tr:`bakhīl`,fr:`avare, radin`,fm:`Adj — schème فَعِيل`,root:`ب خ ل`},
      {w:`لَطِيف`,p:`لطيف`,tr:`laṭīf`,fr:`gentil, aimable, fin`,fm:`Adj — schème فَعِيل`,root:`ل ط ف`},
      {w:`عَنِيد`,p:`عنيد`,tr:`ʿanīd`,fr:`têtu, obstiné`,fm:`Adj — schème فَعِيل`,root:`ع ن د`},
      {w:`صَبُور`,p:`صبور`,tr:`ṣabūr`,fr:`patient, persévérant`,fm:`Adj — schème فَعُول`,root:`ص ب ر`},
      {w:`عَاقِل`,p:`عاقل`,tr:`ʿāqil`,fr:`raisonnable, sensé`,fm:`Participe actif Form I`,root:`ع ق ل`},
      {w:`غَبِيّ`,p:`غبي`,tr:`ghabī`,fr:`stupide, bête`,fm:`Adj — schème فَعِيل`,root:`غ ب ي`},
      {w:`ذَكِيّ`,p:`ذكي`,tr:`dhakī`,fr:`intelligent, vif`,fm:`Adj — schème فَعِيل`,root:`ذ ك و`},
      {w:`نَشِيط`,p:`نشيط`,tr:`nashīṭ`,fr:`actif, énergique`,fm:`Adj — schème فَعِيل`,root:`ن ش ط`},
      {w:`كَسْلَان`,p:`كسلان`,tr:`kaslān`,fr:`paresseux, fainéant`,fm:`Adj — schème فَعْلَان`,root:`ك س ل`},
      {w:`أَمِين`,p:`أمين`,tr:`amīn`,fr:`honnête, digne de confiance`,fm:`Adj — schème فَعِيل`,root:`أ م ن`},
      {w:`كَاذِب`,p:`كاذب`,tr:`kādhib`,fr:`menteur`,fm:`Participe actif Form I`,root:`ك ذ ب`},
      {w:`حَلِيم`,p:`حليم`,tr:`ḥalīm`,fr:`doux, clément, indulgent`,fm:`Adj — schème فَعِيل`,root:`ح ل م`},
      {w:`مَاهِر`,p:`ماهر`,tr:`māhir`,fr:`habile, doué, compétent`,fm:`Adj — participe Form I`,root:`م ه ر`},
      {w:`طَمُوح`,p:`طموح`,tr:`ṭamūḥ`,fr:`ambitieux`,fm:`Adj — schème فَعُول`,root:`ط م ح`},
      {w:`مُخْلِص`,p:`مخلص`,tr:`mukhliṣ`,fr:`sincère, loyal, dévoué`,fm:`Participe actif Form IV`,root:`خ ل ص`},
      {w:`غَيُور`,p:`غيور`,tr:`ghayūr`,fr:`jaloux, zélé`,fm:`Adj — schème فَعُول`,root:`غ ي ر`},
      {w:`حَسُود`,p:`حسود`,tr:`ḥasūd`,fr:`envieux`,fm:`Adj — schème فَعُول`,root:`ح س د`},
      {w:`مُتَوَاضِع`,p:`متواضع`,tr:`mutawāḍiʿ`,fr:`humble, modeste`,fm:`Participe actif Form VI`,root:`و ض ع`},
      {w:`مُتَكَبِّر`,p:`متكبر`,tr:`mutakabbir`,fr:`arrogant, orgueilleux`,fm:`Participe actif Form V`,root:`ك ب ر`}
    ]
  },
  {
    theme:`أَفْعَالٌ أَسَاسِيَّةٌ — Verbes essentiels de base`,
    words:[
      {w:`فَتَحَ`,p:`فتح`,tr:`fataḥa`,fr:`ouvrir`,fm:`Verbe Form I`,root:`ف ت ح`},
      {w:`أَغْلَقَ`,p:`أغلق`,tr:`aghlaq`,fr:`fermer (Form IV)`,fm:`Verbe Form IV`,root:`غ ل ق`},
      {w:`دَخَلَ`,p:`دخل`,tr:`dakhala`,fr:`entrer`,fm:`Verbe Form I`,root:`د خ ل`},
      {w:`خَرَجَ`,p:`خرج`,tr:`kharaja`,fr:`sortir`,fm:`Verbe Form I`,root:`خ ر ج`},
      {w:`وَقَفَ`,p:`وقف`,tr:`waqafa`,fr:`s'arrêter, se lever, se tenir debout`,fm:`Verbe Form I`,root:`و ق ف`},
      {w:`رَكَضَ`,p:`ركض`,tr:`rakaḍa`,fr:`courir`,fm:`Verbe Form I`,root:`ر ك ض`},
      {w:`مَشَى`,p:`مشى`,tr:`mashā`,fr:`marcher`,fm:`Verbe Form I — défectueux`,root:`م ش ي`},
      {w:`جَرَى`,p:`جرى`,tr:`jarā`,fr:`couler, se passer, courir`,fm:`Verbe Form I — défectueux`,root:`ج ر ي`},
      {w:`طَارَ`,p:`طار`,tr:`ṭāra`,fr:`voler (oiseau)`,fm:`Verbe Form I — défectueux`,root:`ط ي ر`},
      {w:`سَبَحَ`,p:`سبح`,tr:`sabaḥa`,fr:`nager`,fm:`Verbe Form I`,root:`س ب ح`},
      {w:`حَمَلَ`,p:`حمل`,tr:`ḥamala`,fr:`porter, transporter`,fm:`Verbe Form I`,root:`ح م ل`},
      {w:`وَضَعَ`,p:`وضع`,tr:`waḍaʿa`,fr:`poser, mettre, placer`,fm:`Verbe Form I`,root:`و ض ع`},
      {w:`رَفَعَ`,p:`رفع`,tr:`rafaʿa`,fr:`lever, soulever, élever`,fm:`Verbe Form I`,root:`ر ف ع`},
      {w:`كَسَرَ`,p:`كسر`,tr:`kasara`,fr:`casser, briser`,fm:`Verbe Form I`,root:`ك س ر`},
      {w:`أَصْلَحَ`,p:`أصلح`,tr:`aṣlaḥa`,fr:`réparer, améliorer`,fm:`Verbe Form IV`,root:`ص ل ح`},
      {w:`نَظَّفَ`,p:`نظف`,tr:`naẓẓafa`,fr:`nettoyer`,fm:`Verbe Form II`,root:`ن ظ ف`},
      {w:`غَسَلَ`,p:`غسل`,tr:`ghassala`,fr:`laver`,fm:`Verbe Form I`,root:`غ س ل`},
      {w:`طَبَخَ`,p:`طبخ`,tr:`ṭabakha`,fr:`cuisiner`,fm:`Verbe Form I`,root:`ط ب خ`},
      {w:`أَكَلَ`,p:`أكل`,tr:`akala`,fr:`manger (rappel)`,fm:`Verbe Form I`,root:`أ ك ل`},
      {w:`شَرِبَ`,p:`شرب`,tr:`shariba`,fr:`boire (rappel)`,fm:`Verbe Form I`,root:`ش ر ب`},
      {w:`لَعِبَ`,p:`لعب`,tr:`laʿiba`,fr:`jouer (rappel)`,fm:`Verbe Form I`,root:`ل ع ب`},
      {w:`قَرَأَ`,p:`قرأ`,tr:`qaraʾa`,fr:`lire (rappel)`,fm:`Verbe Form I`,root:`ق ر أ`},
      {w:`كَتَبَ`,p:`كتب`,tr:`kataba`,fr:`écrire (rappel)`,fm:`Verbe Form I`,root:`ك ت ب`},
      {w:`تَكَلَّمَ`,p:`تكلم`,tr:`takallama`,fr:`parler, s'exprimer`,fm:`Verbe Form V`,root:`ك ل م`},
      {w:`سَمِعَ`,p:`سمع`,tr:`samiʿa`,fr:`entendre, écouter`,fm:`Verbe Form I`,root:`س م ع`},
      {w:`نَظَرَ`,p:`نظر`,tr:`naẓara`,fr:`regarder, voir`,fm:`Verbe Form I`,root:`ن ظ ر`},
      {w:`أَحَسَّ`,p:`أحس`,tr:`aḥassa`,fr:`sentir, ressentir`,fm:`Verbe Form IV`,root:`ح س س`},
      {w:`فَكَّرَ`,p:`فكر`,tr:`fakkara`,fr:`penser, réfléchir`,fm:`Verbe Form II`,root:`ف ك ر`},
      {w:`عَرَفَ`,p:`عرف`,tr:`ʿarafa`,fr:`savoir, connaître`,fm:`Verbe Form I`,root:`ع ر ف`},
      {w:`نَسِيَ`,p:`نسي`,tr:`nasiya`,fr:`oublier`,fm:`Verbe Form I — défectueux`,root:`ن س ي`},
      {w:`تَذَكَّرَ`,p:`تذكر`,tr:`tadhakkara`,fr:`se souvenir, mémoriser`,fm:`Verbe Form V`,root:`ذ ك ر`},
      {w:`اخْتَارَ`,p:`اختار`,tr:`ikhtāra`,fr:`choisir, sélectionner`,fm:`Verbe Form VIII`,root:`خ ي ر`},
      {w:`رَأَى`,p:`رأى`,tr:`raʾā`,fr:`voir, estimer`,fm:`Verbe Form I — hamzé`,root:`ر أ ي`},
      {w:`وَجَدَ`,p:`وجد`,tr:`wajada`,fr:`trouver, ressentir`,fm:`Verbe Form I`,root:`و ج د`},
      {w:`أَخَذَ`,p:`أخذ`,tr:`akhadha`,fr:`prendre, saisir`,fm:`Verbe Form I`,root:`أ خ ذ`},
      {w:`أَعْطَى`,p:`أعطى`,tr:`aʿṭā`,fr:`donner`,fm:`Verbe Form IV — défectueux`,root:`ع ط و`},
      {w:`بَاعَ`,p:`باع`,tr:`bāʿa`,fr:`vendre`,fm:`Verbe Form I — défectueux`,root:`ب ي ع`},
      {w:`اشْتَرَى`,p:`اشترى`,tr:`ishtarā`,fr:`acheter (rappel)`,fm:`Verbe Form VIII`,root:`ش ر ي`},
      {w:`سَأَلَ`,p:`سأل`,tr:`saʾala`,fr:`demander, poser une question`,fm:`Verbe Form I`,root:`س أ ل`},
      {w:`أَجَابَ`,p:`أجاب`,tr:`ajāba`,fr:`répondre`,fm:`Verbe Form IV`,root:`ج و ب`}
    ]
  },
  {
    theme:`الأَرْقَامُ وَالتَّعَابِيرُ الشَّائِعَةُ — Chiffres et expressions courantes`,
    words:[
      {w:`صِفْر`,p:`صفر`,tr:`ṣifr`,fr:`zéro`,fm:`Nom — schème فِعْل`,root:`ص ف ر`},
      {w:`مِئَة`,p:`مئة`,tr:`miʾa`,fr:`cent`,fm:`Nom — schème فِعْلَة`,root:`م أ ة`},
      {w:`أَلْف`,p:`ألف`,tr:`alf`,fr:`mille (pl. آلَاف)`,fm:`Nom — schème فَعْل`,root:`أ ل ف`},
      {w:`مِلْيُون`,p:`مليون`,tr:`milyūn`,fr:`million`,fm:`Nom (emprunt)`,root:`—`},
      {w:`نِصْف`,p:`نصف`,tr:`niṣf`,fr:`moitié, demi`,fm:`Nom — schème فِعْل`,root:`ن ص ف`},
      {w:`رُبُع`,p:`ربع`,tr:`rubuʿ`,fr:`quart`,fm:`Nom — schème فُعُل`,root:`ر ب ع`},
      {w:`ثُلُث`,p:`ثلث`,tr:`thuluth`,fr:`tiers`,fm:`Nom — schème فُعُل`,root:`ث ل ث`},
      {w:`ضِعْف`,p:`ضعف`,tr:`ḍiʿf`,fr:`double, le double`,fm:`Nom — schème فِعْل`,root:`ض ع ف`},
      {w:`عِدَّة`,p:`عدة`,tr:`ʿidda`,fr:`plusieurs, quelques`,fm:`Nom — géminé`,root:`ع د د`},
      {w:`أَكْثَر`,p:`أكثر`,tr:`akthar`,fr:`plus, davantage, majorité`,fm:`Adjectif élatif`,root:`ك ث ر`},
      {w:`أَقَلّ`,p:`أقل`,tr:`aqall`,fr:`moins, minorité`,fm:`Adjectif élatif`,root:`ق ل ل`},
      {w:`كَثِيرًا`,p:`كثيرا`,tr:`kathīran`,fr:`beaucoup (adverbe)`,fm:`Adverbe (acc.)`,root:`ك ث ر`},
      {w:`قَلِيلًا`,p:`قليلا`,tr:`qalīlan`,fr:`peu, un peu (adverbe)`,fm:`Adverbe (acc.)`,root:`ق ل ل`},
      {w:`جِدًّا`,p:`جدا`,tr:`jiddan`,fr:`très, beaucoup (adverbe)`,fm:`Adverbe (géminé)`,root:`ج د د`},
      {w:`فَقَط`,p:`فقط`,tr:`faqaṭ`,fr:`seulement, uniquement`,fm:`Particule`,root:`ف ق ط`},
      {w:`أَيْضًا`,p:`أيضا`,tr:`ayḍan`,fr:`aussi, également`,fm:`Adverbe`,root:`أ ي ض`},
      {w:`لَكِنْ`,p:`لكن`,tr:`lākin`,fr:`mais, cependant`,fm:`Conjonction`,root:`ل ك ن`},
      {w:`لَوْ`,p:`لو`,tr:`law`,fr:`si (hypothétique)`,fm:`Particule conditionnelle`,root:`ل و`},
      {w:`إِذَا`,p:`إذا`,tr:`idhā`,fr:`si, quand (réel)`,fm:`Particule conditionnelle`,root:`أ ذ ي`},
      {w:`حَتَّى`,p:`حتى`,tr:`ḥattā`,fr:`jusqu'à, pour que`,fm:`Préposition/conjonction`,root:`ح ت ي`},
      {w:`رُغْمَ`,p:`رغم`,tr:`rughm`,fr:`malgré`,fm:`Préposition`,root:`ر غ م`},
      {w:`بَدَلًا مِن`,p:`بدلا من`,tr:`badalan min`,fr:`au lieu de`,fm:`Locution prépositionnelle`,root:`ب د ل`},
      {w:`بِسَبَبِ`,p:`بسبب`,tr:`bi-sababi`,fr:`à cause de`,fm:`Prép. + idāfa`,root:`س ب ب`},
      {w:`مِنْ أَجْلِ`,p:`من أجل`,tr:`min ajli`,fr:`pour, dans le but de`,fm:`Locution prépositionnelle`,root:`أ ج ل`},
      {w:`فِي الْحَقِيقَةِ`,p:`في الحقيقة`,tr:`fī l-ḥaqīqa`,fr:`en réalité, en vérité`,fm:`Expression figée`,root:`ح ق ق`},
      {w:`عَلَى سَبِيلِ الْمِثَالِ`,p:`على سبيل المثال`,tr:`ʿalā sabīl al-mithāl`,fr:`par exemple`,fm:`Expression figée`,root:`م ث ل`},
      {w:`مَعَ ذَلِكَ`,p:`مع ذلك`,tr:`maʿa dhālik`,fr:`malgré cela, cependant`,fm:`Expression figée`,root:`ذ ل ك`},
      {w:`فِي الْوَاقِعِ`,p:`في الواقع`,tr:`fī l-wāqiʿ`,fr:`en fait, dans les faits`,fm:`Expression figée`,root:`و ق ع`},
      {w:`مِنَ الْمُمْكِنِ`,p:`من الممكن`,tr:`min al-mumkin`,fr:`il est possible que`,fm:`Expression figée`,root:`م ك ن`},
      {w:`يَعْنِي`,p:`يعني`,tr:`yaʿnī`,fr:`c'est-à-dire, ça veut dire`,fm:`Verbe (emploi figé)`,root:`ع ن ي`}
    ]
  }
];
