/* ═══════════════════════════════════════════════
   VOCABULAIRE THÉMATIQUE — A2
   ~420 mots · 8 thèmes
   RÈGLE : toutes les strings en backticks
═══════════════════════════════════════════════ */
'use strict';

var A2_VOCAB_THEMATIC = [
  {
    theme:`الْمَدِينَةُ وَالْمَرَافِقُ — Ville et services`,
    words:[
      {w:`رَصِيف`,p:`رصيف`,tr:`raṣīf`,fr:`trottoir, quai`,fm:`Nom — schème فَعِيل`,root:`ر ص ف`},
      {w:`تَقَاطُع`,p:`تقاطع`,tr:`taqāṭuʿ`,fr:`carrefour, intersection`,fm:`Masdar Form VI`,root:`ق ط ع`},
      {w:`جِسْر`,p:`جسر`,tr:`jisr`,fr:`pont (pl. جُسُور)`,fm:`Nom — schème فِعْل`,root:`ج س ر`},
      {w:`نَفَق`,p:`نفق`,tr:`nafaq`,fr:`tunnel, souterrain`,fm:`Nom — schème فَعَل`,root:`ن ف ق`},
      {w:`مَيْدَان`,p:`ميدان`,tr:`maydān`,fr:`place, esplanade (pl. مَيَادِين)`,fm:`Nom — schème فَيْعَال`,root:`م ي د`},
      {w:`حَدِيقَة عَامَّة`,p:`حديقة عامة`,tr:`ḥadīqa ʿāmma`,fr:`parc public`,fm:`Idāfa + adjectif`,root:`ح د ق`},
      {w:`مَحَطَّة`,p:`محطة`,tr:`maḥaṭṭa`,fr:`gare, station (pl. مَحَطَّات)`,fm:`Nom de lieu Form II — géminé`,root:`ح ط ط`},
      {w:`مَطَار`,p:`مطار`,tr:`maṭār`,fr:`aéroport`,fm:`Nom de lieu Form I`,root:`ط ي ر`},
      {w:`مَيْنَاء`,p:`ميناء`,tr:`mīnāʾ`,fr:`port (pl. مَوَانِئ)`,fm:`Nom — hamzé`,root:`م ي ن`},
      {w:`بَنْك`,p:`بنك`,tr:`bank`,fr:`banque (pl. بُنُوك)`,fm:`Nom (emprunt)`,root:`—`},
      {w:`صَرَّاف`,p:`صراف`,tr:`ṣarrāf`,fr:`changeur, caissier`,fm:`Nom — schème فَعَّال`,root:`ص ر ف`},
      {w:`صَيْدَلِيَّة`,p:`صيدلية`,tr:`ṣaydaliyya`,fr:`pharmacie`,fm:`Nom — nisba`,root:`ص ي د`},
      {w:`مُسْتَشْفَى`,p:`مستشفى`,tr:`mustashfā`,fr:`hôpital (pl. مُسْتَشْفَيَات)`,fm:`Nom Form X`,root:`ش ف ي`},
      {w:`عِيَادَة`,p:`عيادة`,tr:`ʿiyāda`,fr:`cabinet médical, clinique`,fm:`Masdar Form III`,root:`ع و د`},
      {w:`بَلَدِيَّة`,p:`بلدية`,tr:`baladiyya`,fr:`mairie, municipalité`,fm:`Nisba de بَلَد`,root:`ب ل د`},
      {w:`سَفَارَة`,p:`سفارة`,tr:`sifāra`,fr:`ambassade`,fm:`Masdar Form III`,root:`س ف ر`},
      {w:`شُرْطَة`,p:`شرطة`,tr:`shurṭa`,fr:`police`,fm:`Nom — schème فُعْلَة`,root:`ش ر ط`},
      {w:`إِطْفَائِيَّة`,p:`إطفائية`,tr:`iṭfāʾiyya`,fr:`caserne de pompiers`,fm:`Nisba de إطفاء`,root:`ط ف أ`},
      {w:`مَحْكَمَة`,p:`محكمة`,tr:`maḥkama`,fr:`tribunal, cour`,fm:`Nom de lieu Form I`,root:`ح ك م`},
      {w:`مَكْتَبَة`,p:`مكتبة`,tr:`maktaba`,fr:`bibliothèque, librairie`,fm:`Nom de lieu Form I`,root:`ك ت ب`},
      {w:`مَسْرَح`,p:`مسرح`,tr:`masraḥ`,fr:`théâtre`,fm:`Nom de lieu Form I`,root:`س ر ح`},
      {w:`مَعْرِض`,p:`معرض`,tr:`maʿraḍ`,fr:`exposition, salon`,fm:`Nom de lieu Form I`,root:`ع ر ض`},
      {w:`مَلْعَب`,p:`ملعب`,tr:`malʿab`,fr:`stade, terrain de sport`,fm:`Nom de lieu Form I`,root:`ل ع ب`},
      {w:`حَانُوت`,p:`حانوت`,tr:`ḥānūt`,fr:`boutique, échoppe`,fm:`Nom (emprunt)`,root:`ح ن ت`},
      {w:`سُوبَرْمَارْكِت`,p:`سوبرماركت`,tr:`sūbarmārkit`,fr:`supermarché`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مُوَاصَلَات`,p:`مواصلات`,tr:`muwāṣalāt`,fr:`transports (pl. de مُوَاصَلَة)`,fm:`Pl. de masdar Form III`,root:`و ص ل`},
      {w:`ضِفَاف`,p:`ضفاف`,tr:`ḍifāf`,fr:`rives, bords`,fm:`Pl. de ضِفَّة`,root:`ض ف ف`},
      {w:`حَيّ`,p:`حي`,tr:`ḥayy`,fr:`quartier, voisinage (pl. أَحْيَاء)`,fm:`Nom — géminé`,root:`ح ي ي`},
      {w:`ضَاحِيَة`,p:`ضاحية`,tr:`ḍāḥiya`,fr:`banlieue (pl. ضَوَاحٍ)`,fm:`Participe actif fém.`,root:`ض ح و`},
      {w:`مَدِينَة قَدِيمَة`,p:`مدينة قديمة`,tr:`madīna qadīma`,fr:`vieille ville, médina`,fm:`Syntagme`,root:`ق د م`}
    ]
  },
  {
    theme:`الْعَمَلُ وَالْمِهَنُ — Travail et métiers`,
    words:[
      {w:`طَبِيب`,p:`طبيب`,tr:`ṭabīb`,fr:`médecin (pl. أَطِبَّاء)`,fm:`Adj substantivé — فَعِيل`,root:`ط ب ب`},
      {w:`مُمَرِّض`,p:`ممرض`,tr:`mumarriḍ`,fr:`infirmier`,fm:`Participe actif Form II`,root:`م ر ض`},
      {w:`مُهَنْدِس`,p:`مهندس`,tr:`muhandis`,fr:`ingénieur`,fm:`Participe actif Form IV`,root:`ه ن د`},
      {w:`مَحَامٍ`,p:`محامٍ`,tr:`muḥāmin`,fr:`avocat (pl. مُحَامُون)`,fm:`Participe actif Form III — défectueux`,root:`ح م و`},
      {w:`قَاضٍ`,p:`قاضٍ`,tr:`qāḍin`,fr:`juge (pl. قُضَاة)`,fm:`Participe actif Form I — défectueux`,root:`ق ض و`},
      {w:`مَسْؤُول`,p:`مسؤول`,tr:`masʾūl`,fr:`responsable, fonctionnaire`,fm:`Participe passif Form I`,root:`س أ ل`},
      {w:`مُدِير`,p:`مدير`,tr:`mudīr`,fr:`directeur, manager`,fm:`Participe actif Form IV`,root:`د و ر`},
      {w:`مُوَظَّف`,p:`موظف`,tr:`muwaẓẓaf`,fr:`employé, fonctionnaire`,fm:`Participe passif Form II`,root:`و ظ ف`},
      {w:`تَاجِر`,p:`تاجر`,tr:`tājir`,fr:`commerçant, marchand`,fm:`Participe actif Form III`,root:`ت ج ر`},
      {w:`فَلَّاح`,p:`فلاح`,tr:`fallāḥ`,fr:`paysan, agriculteur`,fm:`Nom — فَعَّال`,root:`ف ل ح`},
      {w:`بَنَّاء`,p:`بناء`,tr:`bannāʾ`,fr:`maçon, constructeur`,fm:`Nom — فَعَّال`,root:`ب ن ي`},
      {w:`كَهْرَبَائِيّ`,p:`كهربائي`,tr:`kahrabāʾī`,fr:`électricien`,fm:`Nisba`,root:`ك ه ر`},
      {w:`سَبَّاك`,p:`سباك`,tr:`sabbāk`,fr:`plombier`,fm:`Nom — فَعَّال`,root:`س ب ك`},
      {w:`نَجَّار`,p:`نجار`,tr:`najjār`,fr:`charpentier, menuisier`,fm:`Nom — فَعَّال`,root:`ن ج ر`},
      {w:`حَدَّاد`,p:`حداد`,tr:`ḥaddād`,fr:`forgeron, ferronnier`,fm:`Nom — فَعَّال — géminé`,root:`ح د د`},
      {w:`طَيَّار`,p:`طيار`,tr:`ṭayyār`,fr:`pilote (aviateur)`,fm:`Nom — فَعَّال`,root:`ط ي ر`},
      {w:`سَائِق`,p:`سائق`,tr:`sāʾiq`,fr:`chauffeur, conducteur`,fm:`Participe actif Form I`,root:`س و ق`},
      {w:`بَحَّار`,p:`بحار`,tr:`baḥḥār`,fr:`marin, navigateur`,fm:`Nom — فَعَّال`,root:`ب ح ر`},
      {w:`حَارِس`,p:`حارس`,tr:`ḥāris`,fr:`gardien, veilleur`,fm:`Participe actif Form I`,root:`ح ر س`},
      {w:`طَبَّاخ`,p:`طباخ`,tr:`ṭabbākh`,fr:`cuisinier, chef`,fm:`Nom — فَعَّال`,root:`ط ب خ`},
      {w:`خَبَّاز`,p:`خباز`,tr:`khabbāz`,fr:`boulanger`,fm:`Nom — فَعَّال`,root:`خ ب ز`},
      {w:`جَزَّار`,p:`جزار`,tr:`jazzār`,fr:`boucher`,fm:`Nom — فَعَّال`,root:`ج ز ر`},
      {w:`فَنِّيّ`,p:`فني`,tr:`fannī`,fr:`technicien`,fm:`Nisba de فَنّ`,root:`ف ن ن`},
      {w:`مُبَرْمِج`,p:`مبرمج`,tr:`mubarmij`,fr:`programmeur`,fm:`Participe actif Form II`,root:`ب ر م`},
      {w:`مُصَمِّم`,p:`مصمم`,tr:`muṣammim`,fr:`designer, concepteur`,fm:`Participe actif Form II`,root:`ص م م`},
      {w:`خَيَّاط`,p:`خياط`,tr:`khayyāṭ`,fr:`tailleur, couturier`,fm:`Nom — فَعَّال`,root:`خ ي ط`},
      {w:`مُعَلِّم`,p:`معلم`,tr:`muʿallim`,fr:`enseignant (rappel)`,fm:`Participe actif Form II`,root:`ع ل م`},
      {w:`أُسْتَاذ`,p:`أستاذ`,tr:`ustādh`,fr:`professeur, maître`,fm:`Nom (emprunt perse/grec)`,root:`أ س ت`},
      {w:`مُحَاسِب`,p:`محاسب`,tr:`muḥāsib`,fr:`comptable`,fm:`Participe actif Form III`,root:`ح س ب`},
      {w:`رَاعٍ`,p:`راعٍ`,tr:`rāʿin`,fr:`berger, pasteur`,fm:`Participe actif Form I — défectueux`,root:`ر ع و`}
    ]
  },
  {
    theme:`الصِّحَّةُ وَالطِّبُّ — Santé et médecine`,
    words:[
      {w:`مَرَض`,p:`مرض`,tr:`maraḍ`,fr:`maladie (pl. أَمْرَاض)`,fm:`Masdar Form I`,root:`م ر ض`},
      {w:`صِحَّة`,p:`صحة`,tr:`ṣiḥḥa`,fr:`santé`,fm:`Nom — géminé`,root:`ص ح ح`},
      {w:`وَجَع`,p:`وجع`,tr:`wajaʿ`,fr:`douleur, souffrance`,fm:`Masdar Form I`,root:`و ج ع`},
      {w:`حُمَّى`,p:`حمى`,tr:`ḥummā`,fr:`fièvre`,fm:`Nom — défectueux — géminé`,root:`ح م م`},
      {w:`سُعَال`,p:`سعال`,tr:`suʿāl`,fr:`toux`,fm:`Masdar Form I`,root:`س ع ل`},
      {w:`زُكَام`,p:`زكام`,tr:`zukām`,fr:`rhume`,fm:`Nom — schème فُعَال`,root:`ز ك م`},
      {w:`صُدَاع`,p:`صداع`,tr:`ṣudāʾ`,fr:`mal de tête, migraine`,fm:`Nom — schème فُعَال`,root:`ص د ع`},
      {w:`دَوَاء`,p:`دواء`,tr:`dawāʾ`,fr:`médicament (pl. أَدْوِيَة)`,fm:`Nom — schème فَعَال`,root:`د و أ`},
      {w:`حَبَّة`,p:`حبة`,tr:`ḥabba`,fr:`pilule, comprimé, graine`,fm:`Nom — géminé`,root:`ح ب ب`},
      {w:`شَرَاب طِبِّيّ`,p:`شراب طبي`,tr:`sharāb ṭibbī`,fr:`sirop médicinal`,fm:`Syntagme`,root:`ش ر ب`},
      {w:`حَقْنَة`,p:`حقنة`,tr:`ḥaqna`,fr:`piqûre, injection`,fm:`Nom — schème فَعْلَة`,root:`ح ق ن`},
      {w:`جَرَاحَة`,p:`جراحة`,tr:`jarāḥa`,fr:`chirurgie`,fm:`Masdar Form I`,root:`ج ر ح`},
      {w:`عَمَلِيَّة`,p:`عملية`,tr:`ʿamaliyya`,fr:`opération chirurgicale`,fm:`Nisba de عَمَل`,root:`ع م ل`},
      {w:`جَبِيرَة`,p:`جبيرة`,tr:`jabīra`,fr:`plâtre, attelle`,fm:`Nom — schème فَعِيلَة`,root:`ج ب ر`},
      {w:`جُرْح`,p:`جرح`,tr:`jurḥ`,fr:`blessure, plaie (pl. جُرُوح)`,fm:`Nom — schème فُعْل`,root:`ج ر ح`},
      {w:`نَزِيف`,p:`نزيف`,tr:`nazīf`,fr:`saignement, hémorragie`,fm:`Nom — schème فَعِيل`,root:`ن ز ف`},
      {w:`تَسَمُّم`,p:`تسمم`,tr:`tasammum`,fr:`intoxication, empoisonnement`,fm:`Masdar Form V`,root:`س م م`},
      {w:`حَسَاسِيَّة`,p:`حساسية`,tr:`ḥasāsiyya`,fr:`allergie, sensibilité`,fm:`Nisba de حَسَّاس`,root:`ح س س`},
      {w:`ضَغْط الدَّم`,p:`ضغط الدم`,tr:`ḍaghṭ ad-dam`,fr:`pression artérielle`,fm:`Idāfa`,root:`ض غ ط`},
      {w:`سُكَّرِيّ`,p:`سكري`,tr:`sukkarī`,fr:`diabète`,fm:`Nisba de سُكَّر`,root:`س ك ر`},
      {w:`تَحْلِيل`,p:`تحليل`,tr:`taḥlīl`,fr:`analyse (médicale)`,fm:`Masdar Form II`,root:`ح ل ل`},
      {w:`أَشْعَّة`,p:`أشعة`,tr:`ashiʿʿa`,fr:`rayons X, radiographie`,fm:`Pl. de شُعَاع`,root:`ش ع ع`},
      {w:`تَطْعِيم`,p:`تطعيم`,tr:`taṭʿīm`,fr:`vaccination`,fm:`Masdar Form II`,root:`ط ع م`},
      {w:`شِفَاء`,p:`شفاء`,tr:`shifāʾ`,fr:`guérison`,fm:`Masdar Form I`,root:`ش ف ي`},
      {w:`وِقَايَة`,p:`وقاية`,tr:`wiqāya`,fr:`prévention, protection`,fm:`Masdar Form I`,root:`و ق ي`},
      {w:`نَظَّافَة`,p:`نظافة`,tr:`naẓāfa`,fr:`hygiène, propreté`,fm:`Masdar Form I`,root:`ن ظ ف`},
      {w:`رَاحَة`,p:`راحة`,tr:`rāḥa`,fr:`repos, confort`,fm:`Masdar Form I`,root:`ر و ح`},
      {w:`أَرَق`,p:`أرق`,tr:`araq`,fr:`insomnie`,fm:`Masdar Form I`,root:`أ ر ق`},
      {w:`نَفْسِيَّة`,p:`نفسية`,tr:`nafsiyya`,fr:`psychologie, état psychologique`,fm:`Nisba de نَفْس`,root:`ن ف س`},
      {w:`ضَغْط نَفْسِيّ`,p:`ضغط نفسي`,tr:`ḍaghṭ nafsī`,fr:`stress, pression psychologique`,fm:`Syntagme`,root:`ض غ ط`}
    ]
  },
  {
    theme:`التِّكْنُولُوجِيَا — Technologie et numérique`,
    words:[
      {w:`هَاتِف`,p:`هاتف`,tr:`hātif`,fr:`téléphone (pl. هَوَاتِف)`,fm:`Participe actif Form I`,root:`ه ت ف`},
      {w:`هَاتِف ذَكِيّ`,p:`هاتف ذكي`,tr:`hātif dhakī`,fr:`smartphone`,fm:`Syntagme`,root:`ه ت ف`},
      {w:`حَاسُوب`,p:`حاسوب`,tr:`ḥāsūb`,fr:`ordinateur`,fm:`Nom — schème فَاعُول`,root:`ح س ب`},
      {w:`لَوْحِيّ`,p:`لوحي`,tr:`lawḥī`,fr:`tablette numérique`,fm:`Nisba de لَوْح`,root:`ل و ح`},
      {w:`شَاشَة`,p:`شاشة`,tr:`shāsha`,fr:`écran (pl. شَاشَات)`,fm:`Nom`,root:`ش ش`},
      {w:`لُوحَة مَفَاتِيح`,p:`لوحة مفاتيح`,tr:`lawḥat mafātīḥ`,fr:`clavier`,fm:`Idāfa`,root:`ف ت ح`},
      {w:`فَأْرَة`,p:`فأرة`,tr:`faʾra`,fr:`souris (d'ordinateur)`,fm:`Nom — schème فَعْلَة`,root:`ف أ ر`},
      {w:`طَابِعَة`,p:`طابعة`,tr:`ṭābiʿa`,fr:`imprimante`,fm:`Participe actif fém. Form I`,root:`ط ب ع`},
      {w:`إِنْتَرْنِت`,p:`انترنت`,tr:`intarnit`,fr:`internet`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مَوْقِع إِلِكْتُرُونِيّ`,p:`موقع إلكتروني`,tr:`mawqiʿ ilktrūnī`,fr:`site web`,fm:`Syntagme`,root:`و ق ع`},
      {w:`تَطْبِيق`,p:`تطبيق`,tr:`taṭbīq`,fr:`application (app)`,fm:`Masdar Form II`,root:`ط ب ق`},
      {w:`كَلِمَة السِّرّ`,p:`كلمة السر`,tr:`kalimat as-sirr`,fr:`mot de passe`,fm:`Idāfa`,root:`س ر ر`},
      {w:`بَرِيد إِلِكْتُرُونِيّ`,p:`بريد إلكتروني`,tr:`barīd ilktrūnī`,fr:`email, courriel`,fm:`Syntagme`,root:`ب ر د`},
      {w:`شَبَكَة`,p:`شبكة`,tr:`shabaka`,fr:`réseau (pl. شَبَكَات)`,fm:`Nom — schème فَعَلَة`,root:`ش ب ك`},
      {w:`بَثّ`,p:`بث`,tr:`bathth`,fr:`diffusion, streaming`,fm:`Masdar Form I — géminé`,root:`ب ث ث`},
      {w:`تَنْزِيل`,p:`تنزيل`,tr:`tanzīl`,fr:`téléchargement`,fm:`Masdar Form II`,root:`ن ز ل`},
      {w:`رَفْع`,p:`رفع`,tr:`rafʿ`,fr:`upload, envoi`,fm:`Masdar Form I`,root:`ر ف ع`},
      {w:`نَسْخَة احْتِيَاطِيَّة`,p:`نسخة احتياطية`,tr:`nuskha iḥtiyāṭiyya`,fr:`sauvegarde, backup`,fm:`Syntagme`,root:`ن س خ`},
      {w:`فَيْرُوس`,p:`فيروس`,tr:`fayrūs`,fr:`virus (informatique)`,fm:`Nom (emprunt)`,root:`—`},
      {w:`كَامِيرَا`,p:`كاميرا`,tr:`kāmīrā`,fr:`caméra, appareil photo`,fm:`Nom (emprunt)`,root:`—`},
      {w:`شَاحِن`,p:`شاحن`,tr:`shāḥin`,fr:`chargeur (électronique)`,fm:`Participe actif Form I`,root:`ش ح ن`},
      {w:`بَطَّارِيَّة`,p:`بطارية`,tr:`baṭṭāriyya`,fr:`batterie, pile`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مِقْيَاس ذَكَاء`,p:`مقياس ذكاء`,tr:`miqyās dhakāʾ`,fr:`test d'intelligence`,fm:`Syntagme`,root:`ق ي س`},
      {w:`ذَاكِرَة`,p:`ذاكرة`,tr:`dhākira`,fr:`mémoire (informatique et mentale)`,fm:`Participe actif fém. Form I`,root:`ذ ك ر`},
      {w:`مَنَصَّة`,p:`منصة`,tr:`manassa`,fr:`plateforme numérique`,fm:`Nom — schème مَفْعَلَة`,root:`ن ص ص`},
      {w:`تَقَنِيَّة`,p:`تقنية`,tr:`taqniyya`,fr:`technologie, technique`,fm:`Nisba de تِقَن`,root:`ت ق ن`},
      {w:`رَقْمَنَة`,p:`رقمنة`,tr:`raqmana`,fr:`numérisation`,fm:`Masdar (néologisme)`,root:`ر ق م`},
      {w:`اصْطِنَاعِيّ`,p:`اصطناعي`,tr:`iṣṭināʿī`,fr:`artificiel, synthétique`,fm:`Nisba de اصطناع`,root:`ص ن ع`},
      {w:`خَوَارِزْمِيَّة`,p:`خوارزمية`,tr:`khawārizmiyya`,fr:`algorithme`,fm:`Nisba de الخوارزمي`,root:`—`},
      {w:`بَيَانَات`,p:`بيانات`,tr:`bayānāt`,fr:`données, data`,fm:`Pl. de بَيَان`,root:`ب ي ن`}
    ]
  },
  {
    theme:`الإِسْلَامُ وَالْعِبَادَةُ — مُتَوَسِّط — Islam et pratique (intermédiaire)`,
    words:[
      {w:`تَوْحِيد`,p:`توحيد`,tr:`tawḥīd`,fr:`monothéisme, unicité de Dieu`,fm:`Masdar Form II`,root:`و ح د`},
      {w:`عَقِيدَة`,p:`عقيدة`,tr:`ʿaqīda`,fr:`croyance, doctrine (pl. عَقَائِد)`,fm:`Nom — فَعِيلَة`,root:`ع ق د`},
      {w:`فِقْه`,p:`فقه`,tr:`fiqh`,fr:`jurisprudence islamique`,fm:`Masdar Form I`,root:`ف ق ه`},
      {w:`تَفْسِير`,p:`تفسير`,tr:`tafsīr`,fr:`exégèse coranique`,fm:`Masdar Form II`,root:`ف س ر`},
      {w:`تَجْوِيد`,p:`تجويد`,tr:`tajwīd`,fr:`psalmodie coranique`,fm:`Masdar Form II`,root:`ج و د`},
      {w:`صِرَاط مُسْتَقِيم`,p:`صراط مستقيم`,tr:`ṣirāṭ mustaqīm`,fr:`droit chemin (terme coranique)`,fm:`Syntagme`,root:`ص ر ط`},
      {w:`جَنَّة`,p:`جنة`,tr:`janna`,fr:`paradis`,fm:`Nom — géminé`,root:`ج ن ن`},
      {w:`نَار`,p:`نار`,tr:`nār`,fr:`feu, enfer (pl. نِيرَان)`,fm:`Nom fém.`,root:`ن و ر`},
      {w:`يَوْمُ الْقِيَامَة`,p:`يوم القيامة`,tr:`yawm al-qiyāma`,fr:`Jour de la Résurrection`,fm:`Idāfa`,root:`ق و م`},
      {w:`مَلَائِكَة`,p:`ملائكة`,tr:`malāʾika`,fr:`anges (pl. de مَلَك)`,fm:`Pl. brisé`,root:`م ل ك`},
      {w:`شَيْطَان`,p:`شيطان`,tr:`shayṭān`,fr:`diable, Satan`,fm:`Nom — schème فَيْعَال`,root:`ش ط ن`},
      {w:`ذِكْر`,p:`ذكر`,tr:`dhikr`,fr:`invocation, souvenir de Dieu`,fm:`Masdar Form I`,root:`ذ ك ر`},
      {w:`دُعَاء`,p:`دعاء`,tr:`duʿāʾ`,fr:`prière, invocation personnelle`,fm:`Masdar Form I`,root:`د ع و`},
      {w:`اسْتِغْفَار`,p:`استغفار`,tr:`istighfār`,fr:`demande de pardon`,fm:`Masdar Form X`,root:`غ ف ر`},
      {w:`تَوْبَة`,p:`توبة`,tr:`tawba`,fr:`repentir`,fm:`Masdar Form I`,root:`ت و ب`},
      {w:`صَدَقَة`,p:`صدقة`,tr:`ṣadaqa`,fr:`aumône volontaire`,fm:`Nom — فَعَلَة`,root:`ص د ق`},
      {w:`سُنَّة`,p:`سنة`,tr:`sunna`,fr:`tradition prophétique`,fm:`Nom — géminé`,root:`س ن ن`},
      {w:`حَلَال`,p:`حلال`,tr:`ḥalāl`,fr:`licite, permis`,fm:`Adjectif`,root:`ح ل ل`},
      {w:`حَرَام`,p:`حرام`,tr:`ḥarām`,fr:`illicite, interdit`,fm:`Adjectif`,root:`ح ر م`},
      {w:`مَكْرُوه`,p:`مكروه`,tr:`makrūh`,fr:`déconseillé (acte)`,fm:`Participe passif Form I`,root:`ك ر ه`},
      {w:`وَاجِب`,p:`واجب`,tr:`wājib`,fr:`obligatoire (acte religieux)`,fm:`Participe actif Form I`,root:`و ج ب`},
      {w:`مُسْتَحَبّ`,p:`مستحب`,tr:`mustaḥabb`,fr:`recommandé`,fm:`Participe passif Form X`,root:`ح ب ب`},
      {w:`نِيَّة`,p:`نية`,tr:`niyya`,fr:`intention (pilier de l'acte)`,fm:`Nom — géminé`,root:`ن و ي`},
      {w:`طَهَارَة`,p:`طهارة`,tr:`ṭahāra`,fr:`pureté rituelle`,fm:`Masdar Form I`,root:`ط ه ر`},
      {w:`نَجَاسَة`,p:`نجاسة`,tr:`najāsa`,fr:`impureté rituelle`,fm:`Nom — فَعَالَة`,root:`ن ج س`},
      {w:`مَسْجِد`,p:`مسجد`,tr:`masjid`,fr:`mosquée (pl. مَسَاجِد)`,fm:`Nom de lieu Form I`,root:`س ج د`},
      {w:`إِمَام`,p:`إمام`,tr:`imām`,fr:`imam, guide (pl. أَئِمَّة)`,fm:`Nom — فِعَال`,root:`أ م م`},
      {w:`خُطْبَة الْجُمُعَة`,p:`خطبة الجمعة`,tr:`khuṭbat al-jumuʿa`,fr:`sermon du vendredi`,fm:`Idāfa`,root:`خ ط ب`},
      {w:`مِحْرَاب`,p:`محراب`,tr:`miḥrāb`,fr:`niche de la mosquée (direction)`,fm:`Nom — مِفْعَال`,root:`ح ر ب`},
      {w:`مِنْبَر`,p:`منبر`,tr:`minbar`,fr:`minbar, chaire (pl. مَنَابِر)`,fm:`Nom — مِفْعَل`,root:`ن ب ر`}
    ]
  },
  {
    theme:`الدِّرَاسَةُ وَالتَّعْلِيمُ — Études et éducation`,
    words:[
      {w:`جَامِعَة`,p:`جامعة`,tr:`jāmiʿa`,fr:`université`,fm:`Participe actif fém. Form I`,root:`ج م ع`},
      {w:`كُلِّيَّة`,p:`كلية`,tr:`kulliyya`,fr:`faculté`,fm:`Adj substantivé — géminé`,root:`ك ل ل`},
      {w:`قِسْم`,p:`قسم`,tr:`qism`,fr:`département, section (pl. أَقْسَام)`,fm:`Nom — schème فِعْل`,root:`ق س م`},
      {w:`شَهَادَة`,p:`شهادة`,tr:`shahāda`,fr:`diplôme, attestation`,fm:`Masdar Form I`,root:`ش ه د`},
      {w:`دَرَجَة`,p:`درجة`,tr:`daraja`,fr:`note, grade, degré`,fm:`Nom — فَعَلَة`,root:`د ر ج`},
      {w:`امْتِحَان`,p:`امتحان`,tr:`imtiḥān`,fr:`examen, test`,fm:`Masdar Form VIII`,root:`م ح ن`},
      {w:`مَادَّة`,p:`مادة`,tr:`mādda`,fr:`matière scolaire (pl. مَوَادّ)`,fm:`Nom — géminé`,root:`م و د`},
      {w:`مَنْهَج`,p:`منهج`,tr:`manhaj`,fr:`programme scolaire`,fm:`Nom — مَفْعَل`,root:`ن ه ج`},
      {w:`فَصْل دِرَاسِيّ`,p:`فصل دراسي`,tr:`faṣl dirāsī`,fr:`semestre, période scolaire`,fm:`Syntagme`,root:`ف ص ل`},
      {w:`مَكْتَبَة`,p:`مكتبة`,tr:`maktaba`,fr:`bibliothèque, librairie`,fm:`Nom de lieu`,root:`ك ت ب`},
      {w:`قَامُوس`,p:`قاموس`,tr:`qāmūs`,fr:`dictionnaire`,fm:`Nom (emprunt)`,root:`ق م س`},
      {w:`مَرْجِع`,p:`مرجع`,tr:`marjiʿ`,fr:`référence, ouvrage de référence`,fm:`Nom de lieu Form I`,root:`ر ج ع`},
      {w:`رِسَالَة`,p:`رسالة`,tr:`risāla`,fr:`mémoire, thèse, lettre`,fm:`Nom — فِعَالَة`,root:`ر س ل`},
      {w:`أُطْرُوحَة`,p:`أطروحة`,tr:`uṭrūḥa`,fr:`thèse de doctorat`,fm:`Nom — أُفْعُولَة`,root:`ط ر ح`},
      {w:`بَحْث`,p:`بحث`,tr:`baḥth`,fr:`recherche, étude (pl. بُحُوث)`,fm:`Masdar Form I`,root:`ب ح ث`},
      {w:`مُقَرَّر`,p:`مقرر`,tr:`muqarrar`,fr:`manuel scolaire, décidé`,fm:`Participe passif Form II`,root:`ق ر ر`},
      {w:`مُحَاضَرَة`,p:`محاضرة`,tr:`muḥāḍara`,fr:`cours magistral, conférence`,fm:`Masdar Form III`,root:`ح ض ر`},
      {w:`نَدْوَة`,p:`ندوة`,tr:`nadwa`,fr:`séminaire, symposium`,fm:`Nom`,root:`ن د و`},
      {w:`تَخَصُّص`,p:`تخصص`,tr:`takhaṣṣuṣ`,fr:`spécialisation`,fm:`Masdar Form V`,root:`خ ص ص`},
      {w:`مُبْتَعَث`,p:`مبتعث`,tr:`mubtaʿath`,fr:`étudiant boursier à l'étranger`,fm:`Participe passif Form VIII`,root:`ب ع ث`},
      {w:`تَرْبِيَة`,p:`تربية`,tr:`tarbiya`,fr:`éducation, pédagogie`,fm:`Masdar Form II`,root:`ر ب و`},
      {w:`تَعَلُّم`,p:`تعلم`,tr:`taʿallum`,fr:`apprentissage`,fm:`Masdar Form V`,root:`ع ل م`},
      {w:`تَدْرِيس`,p:`تدريس`,tr:`tadrīs`,fr:`enseignement`,fm:`Masdar Form II`,root:`د ر س`},
      {w:`اخْتِبَار`,p:`اختبار`,tr:`ikhtibār`,fr:`test, examen`,fm:`Masdar Form VIII`,root:`خ ب ر`},
      {w:`تَقْيِيم`,p:`تقييم`,tr:`taqyīm`,fr:`évaluation, notation`,fm:`Masdar Form II`,root:`ق ي م`},
      {w:`مَنْحَة`,p:`منحة`,tr:`minḥa`,fr:`bourse d'études`,fm:`Nom — فَعْلَة`,root:`م ن ح`},
      {w:`رُسُوم دِرَاسِيَّة`,p:`رسوم دراسية`,tr:`rusūm dirāsiyya`,fr:`frais de scolarité`,fm:`Pl. + nisba`,root:`ر س م`},
      {w:`طَالِب مُتَفَوِّق`,p:`طالب متفوق`,tr:`ṭālib mutafawwiq`,fr:`étudiant excellent`,fm:`Syntagme`,root:`ف و ق`},
      {w:`وَلِيّ أَمْر`,p:`ولي أمر`,tr:`walī amr`,fr:`tuteur, parent d'élève`,fm:`Idāfa`,root:`و ل ي`},
      {w:`تَعَاوُن`,p:`تعاون`,tr:`taʿāwun`,fr:`coopération, collaboration`,fm:`Masdar Form VI`,root:`ع و ن`}
    ]
  },
  {
    theme:`المُجْتَمَعُ وَالشَّأْنُ الاجْتِمَاعِيُّ — Société et vie sociale`,
    words:[
      {w:`مُجْتَمَع`,p:`مجتمع`,tr:`mujtamaʿ`,fr:`société, communauté`,fm:`Participe passif Form VIII`,root:`ج م ع`},
      {w:`مَدَنِيّ`,p:`مدني`,tr:`madanī`,fr:`civil, citoyen`,fm:`Nisba de مَدِينَة`,root:`م د ن`},
      {w:`مُوَاطِن`,p:`مواطن`,tr:`muwāṭin`,fr:`citoyen, résident`,fm:`Participe actif Form III`,root:`و ط ن`},
      {w:`جِنْسِيَّة`,p:`جنسية`,tr:`jinsiyya`,fr:`nationalité, citoyenneté`,fm:`Nisba de جِنْس`,root:`ج ن س`},
      {w:`إِقَامَة`,p:`إقامة`,tr:`iqāma`,fr:`résidence (titre de séjour)`,fm:`Masdar Form IV`,root:`ق و م`},
      {w:`تَعَدُّد`,p:`تعدد`,tr:`taʿaddud`,fr:`pluralité, diversité`,fm:`Masdar Form V`,root:`ع د د`},
      {w:`تَنَوُّع`,p:`تنوع`,tr:`tanawwuʿ`,fr:`diversité, variété`,fm:`Masdar Form V`,root:`ن و ع`},
      {w:`تَسَامُح`,p:`تسامح`,tr:`tasāmuḥ`,fr:`tolérance, indulgence`,fm:`Masdar Form VI`,root:`س م ح`},
      {w:`مُسَاوَاة`,p:`مساواة`,tr:`musāwāh`,fr:`égalité`,fm:`Masdar Form III`,root:`س و ي`},
      {w:`عَدَالَة`,p:`عدالة`,tr:`ʿadāla`,fr:`justice`,fm:`Masdar Form I`,root:`ع د ل`},
      {w:`حَقّ`,p:`حق`,tr:`ḥaqq`,fr:`droit, vérité (pl. حُقُوق)`,fm:`Nom — géminé`,root:`ح ق ق`},
      {w:`وَاجِب`,p:`واجب`,tr:`wājib`,fr:`devoir, obligation`,fm:`Participe actif Form I`,root:`و ج ب`},
      {w:`مَسْؤُولِيَّة`,p:`مسؤولية`,tr:`masʾūliyya`,fr:`responsabilité`,fm:`Nisba de مسؤول`,root:`س أ ل`},
      {w:`تَطَوُّع`,p:`تطوع`,tr:`taṭawwuʿ`,fr:`bénévolat, volontariat`,fm:`Masdar Form V`,root:`ط و ع`},
      {w:`مُتَطَوِّع`,p:`متطوع`,tr:`mutaṭawwiʿ`,fr:`bénévole`,fm:`Participe actif Form V`,root:`ط و ع`},
      {w:`جَمْعِيَّة`,p:`جمعية`,tr:`jamʿiyya`,fr:`association, ONG`,fm:`Nisba de جَمْع`,root:`ج م ع`},
      {w:`احْتِجَاج`,p:`احتجاج`,tr:`iḥtijāj`,fr:`protestation, manifestation`,fm:`Masdar Form VIII`,root:`ح ج ج`},
      {w:`مُظَاهَرَة`,p:`مظاهرة`,tr:`muẓāhara`,fr:`manifestation, défilé`,fm:`Masdar Form III`,root:`ظ ه ر`},
      {w:`حُرِّيَّة`,p:`حرية`,tr:`ḥurriyya`,fr:`liberté`,fm:`Nom — nisba de حُرّ`,root:`ح ر ر`},
      {w:`أَمَان`,p:`أمان`,tr:`amān`,fr:`sécurité, paix`,fm:`Masdar Form IV`,root:`أ م ن`},
      {w:`نِظَام`,p:`نظام`,tr:`niẓām`,fr:`système, ordre (pl. أَنْظِمَة)`,fm:`Nom — فِعَال`,root:`ن ظ م`},
      {w:`قَانُون`,p:`قانون`,tr:`qānūn`,fr:`loi, code (pl. قَوَانِين)`,fm:`Nom`,root:`ق ن ن`},
      {w:`دَسْتُور`,p:`دستور`,tr:`dustūr`,fr:`constitution`,fm:`Nom (emprunt persan)`,root:`—`},
      {w:`حُكُومَة`,p:`حكومة`,tr:`ḥukūma`,fr:`gouvernement`,fm:`Masdar Form II`,root:`ح ك م`},
      {w:`دَوْلَة`,p:`دولة`,tr:`dawla`,fr:`État, nation (pl. دُوَل)`,fm:`Nom — فَعْلَة`,root:`د و ل`},
      {w:`شَعْب`,p:`شعب`,tr:`shaʿb`,fr:`peuple (pl. شُعُوب)`,fm:`Nom — فَعْل`,root:`ش ع ب`},
      {w:`بَرْلَمَان`,p:`برلمان`,tr:`barlumān`,fr:`parlement`,fm:`Nom (emprunt)`,root:`—`},
      {w:`انْتِخَاب`,p:`انتخاب`,tr:`intikāb`,fr:`élection, vote`,fm:`Masdar Form VIII`,root:`ن خ ب`},
      {w:`مُرَشَّح`,p:`مرشح`,tr:`murashshah`,fr:`candidat`,fm:`Participe passif Form II`,root:`ر ش ح`},
      {w:`فَسَاد`,p:`فساد`,tr:`fasād`,fr:`corruption, corruption`,fm:`Masdar Form I`,root:`ف س د`}
    ]
  },
  {
    theme:`الرِّيَاضَةُ وَالتَّرْفِيهُ — Sport et loisirs`,
    words:[
      {w:`كُرَة الْقَدَم`,p:`كرة القدم`,tr:`kurat al-qadam`,fr:`football`,fm:`Idāfa`,root:`ق د م`},
      {w:`كُرَة السَّلَّة`,p:`كرة السلة`,tr:`kurat as-salla`,fr:`basketball`,fm:`Idāfa`,root:`س ل ل`},
      {w:`كُرَة الطَّائِرَة`,p:`كرة الطائرة`,tr:`kurat aṭ-ṭāʾira`,fr:`volleyball`,fm:`Idāfa`,root:`ط ي ر`},
      {w:`تَنِس`,p:`تنس`,tr:`tinis`,fr:`tennis`,fm:`Nom (emprunt)`,root:`—`},
      {w:`سِبَاحَة`,p:`سباحة`,tr:`sibāḥa`,fr:`natation`,fm:`Masdar Form I`,root:`س ب ح`},
      {w:`مَلَاكَمَة`,p:`ملاكمة`,tr:`mulākama`,fr:`boxe`,fm:`Masdar Form III`,root:`ل ك م`},
      {w:`جُودُو`,p:`جودو`,tr:`jūdū`,fr:`judo`,fm:`Nom (emprunt japonais)`,root:`—`},
      {w:`رِيَاضَة`,p:`رياضة`,tr:`riyāḍa`,fr:`sport (sens général)`,fm:`Nom — فِعَالَة`,root:`ر و ض`},
      {w:`فَرِيق`,p:`فريق`,tr:`farīq`,fr:`équipe (pl. فِرَق)`,fm:`Nom — فَعِيل`,root:`ف ر ق`},
      {w:`بَطَل`,p:`بطل`,tr:`baṭal`,fr:`champion, héros (pl. أَبْطَال)`,fm:`Nom — فَعَل`,root:`ب ط ل`},
      {w:`بُطُولَة`,p:`بطولة`,tr:`buṭūla`,fr:`championnat, titre`,fm:`Masdar Form I`,root:`ب ط ل`},
      {w:`مُبَارَاة`,p:`مباراة`,tr:`mubārāh`,fr:`match, compétition`,fm:`Masdar Form III`,root:`ب ر ي`},
      {w:`نَتِيجَة`,p:`نتيجة`,tr:`natīja`,fr:`résultat, score`,fm:`Nom — فَعِيلَة`,root:`ن ت ج`},
      {w:`تَعَادُل`,p:`تعادل`,tr:`taʿādul`,fr:`match nul, égalité`,fm:`Masdar Form VI`,root:`ع د ل`},
      {w:`فَوْز`,p:`فوز`,tr:`fawz`,fr:`victoire, succès`,fm:`Masdar Form I`,root:`ف و ز`},
      {w:`هَزِيمَة`,p:`هزيمة`,tr:`hazīma`,fr:`défaite`,fm:`Nom — فَعِيلَة`,root:`ه ز م`},
      {w:`حَكَم`,p:`حكم`,tr:`ḥakam`,fr:`arbitre`,fm:`Nom — فَعَل`,root:`ح ك م`},
      {w:`مُدَرِّب`,p:`مدرب`,tr:`mudarrib`,fr:`entraîneur`,fm:`Participe actif Form II`,root:`د ر ب`},
      {w:`جُمْهُور`,p:`جمهور`,tr:`jumhūr`,fr:`public, supporters`,fm:`Nom — فُعْلُول`,root:`ج م ه`},
      {w:`مَلْعَب`,p:`ملعب`,tr:`malʿab`,fr:`stade, terrain (pl. مَلَاعِب)`,fm:`Nom de lieu`,root:`ل ع ب`},
      {w:`سِينَمَا`,p:`سينما`,tr:`sīnimā`,fr:`cinéma`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مُوسِيقَى`,p:`موسيقى`,tr:`mūsīqā`,fr:`musique`,fm:`Nom (emprunt grec)`,root:`—`},
      {w:`مَسْرَح`,p:`مسرح`,tr:`masraḥ`,fr:`théâtre`,fm:`Nom de lieu`,root:`س ر ح`},
      {w:`رِوَايَة`,p:`رواية`,tr:`riwāya`,fr:`roman, récit (pl. رِوَايَات)`,fm:`Masdar Form I`,root:`ر و ي`},
      {w:`دِيوَان`,p:`ديوان`,tr:`dīwān`,fr:`recueil de poèmes, divan`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مَعْرِض`,p:`معرض`,tr:`maʿraḍ`,fr:`exposition, galerie`,fm:`Nom de lieu`,root:`ع ر ض`},
      {w:`تَصْوِير`,p:`تصوير`,tr:`taṣwīr`,fr:`photographie`,fm:`Masdar Form II`,root:`ص و ر`},
      {w:`رَسْم`,p:`رسم`,tr:`rasm`,fr:`dessin, peinture`,fm:`Masdar Form I`,root:`ر س م`},
      {w:`نَحْت`,p:`نحت`,tr:`naḥt`,fr:`sculpture`,fm:`Masdar Form I`,root:`ن ح ت`},
      {w:`طِوَاف`,p:`طواف`,tr:`ṭawāf`,fr:`randonnée, marche`,fm:`Masdar Form I`,root:`ط و ف`}
    ]
  }
];
