/* ═══════════════════════════════════════════════
   VOCABULAIRE THÉMATIQUE — B1
   ~320 mots · 8 thèmes
   RÈGLE : toutes les strings en backticks
═══════════════════════════════════════════════ */
'use strict';
var B1_VOCAB_THEMATIC = [
  {
    theme:`الاقْتِصَادُ وَالتِّجَارَةُ — Économie et commerce`,
    words:[
      {w:`اقْتِصَاد`,p:`اقتصاد`,tr:`iqtiṣād`,fr:`économie`,fm:`Masdar Form VIII`,root:`ق ص د`},
      {w:`تِجَارَة`,p:`تجارة`,tr:`tijāra`,fr:`commerce`,fm:`Masdar Form I — défectueux`,root:`ت ج ر`},
      {w:`سُوق`,p:`سوق`,tr:`sūq`,fr:`marché, bazar (pl. أَسْوَاق)`,fm:`Nom — فَعْل`,root:`س و ق`},
      {w:`عَرْض وَطَلَب`,p:`عرض وطلب`,tr:`ʿarḍ wa-ṭalab`,fr:`offre et demande`,fm:`Syntagme`,root:`ع ر ض`},
      {w:`إِنْتَاج`,p:`إنتاج`,tr:`intāj`,fr:`production`,fm:`Masdar Form IV`,root:`ن ت ج`},
      {w:`اسْتِهْلَاك`,p:`استهلاك`,tr:`istihlāk`,fr:`consommation`,fm:`Masdar Form X`,root:`ه ل ك`},
      {w:`تَضَخُّم`,p:`تضخم`,tr:`taḍakhkhum`,fr:`inflation`,fm:`Masdar Form V`,root:`ض خ م`},
      {w:`رَكُود`,p:`ركود`,tr:`rukūd`,fr:`récession, stagnation`,fm:`Masdar Form I`,root:`ر ك د`},
      {w:`نُمُوّ`,p:`نمو`,tr:`numuww`,fr:`croissance (économique)`,fm:`Masdar Form I — géminé`,root:`ن م و`},
      {w:`نَاتِج مَحَلِّيّ`,p:`ناتج محلي`,tr:`nātij maḥallī`,fr:`PIB (produit intérieur brut)`,fm:`Syntagme`,root:`ن ت ج`},
      {w:`مِيزَانِيَّة`,p:`ميزانية`,tr:`mīzāniyya`,fr:`budget`,fm:`Nisba de مِيزَان`,root:`و ز ن`},
      {w:`عَجْز`,p:`عجز`,tr:`ʿajz`,fr:`déficit`,fm:`Masdar Form I`,root:`ع ج ز`},
      {w:`فَائِض`,p:`فائض`,tr:`fāʾiḍ`,fr:`excédent, surplus`,fm:`Participe actif Form I`,root:`ف ي ض`},
      {w:`ضَرِيبَة`,p:`ضريبة`,tr:`ḍarība`,fr:`impôt, taxe (pl. ضَرَائِب)`,fm:`Nom — فَعِيلَة`,root:`ض ر ب`},
      {w:`جَمَارِك`,p:`جمارك`,tr:`jamārik`,fr:`douanes`,fm:`Pl. de جُمْرُك`,root:`ج م ر`},
      {w:`اسْتِثْمَار`,p:`استثمار`,tr:`istithmār`,fr:`investissement`,fm:`Masdar Form X`,root:`ث م ر`},
      {w:`مُسْتَثْمِر`,p:`مستثمر`,tr:`mustathmir`,fr:`investisseur`,fm:`Participe actif Form X`,root:`ث م ر`},
      {w:`عَائِد`,p:`عائد`,tr:`ʿāʾid`,fr:`revenu, rendement`,fm:`Participe actif Form I`,root:`ع و د`},
      {w:`رِبْح`,p:`ربح`,tr:`ribḥ`,fr:`profit, bénéfice (pl. أَرْبَاح)`,fm:`Masdar Form I`,root:`ر ب ح`},
      {w:`خَسَارَة`,p:`خسارة`,tr:`khsāra`,fr:`perte, dommage`,fm:`Masdar Form I`,root:`خ س ر`},
      {w:`شَرِكَة`,p:`شركة`,tr:`sharika`,fr:`entreprise, société`,fm:`Masdar Form I`,root:`ش ر ك`},
      {w:`مُؤَسَّسَة`,p:`مؤسسة`,tr:`muʾassasa`,fr:`institution, établissement`,fm:`Participe passif Form II fém.`,root:`أ س س`},
      {w:`مُشْتَرٍ`,p:`مشتر`,tr:`mushtarin`,fr:`acheteur`,fm:`Participe actif Form VIII — défectueux`,root:`ش ر ي`},
      {w:`بَائِع`,p:`بائع`,tr:`bāʾiʿ`,fr:`vendeur`,fm:`Participe actif Form I`,root:`ب ي ع`},
      {w:`فَاتُورَة`,p:`فاتورة`,tr:`fātūra`,fr:`facture, note`,fm:`Nom (emprunt)`,root:`—`},
      {w:`عَقْد`,p:`عقد`,tr:`ʿaqd`,fr:`contrat (pl. عُقُود)`,fm:`Nom — فَعْل`,root:`ع ق د`},
      {w:`بَنْك مَرْكَزِيّ`,p:`بنك مركزي`,tr:`bank markazī`,fr:`banque centrale`,fm:`Syntagme`,root:`م ر ك`},
      {w:`سَنَد`,p:`سند`,tr:`sanad`,fr:`obligation, bon`,fm:`Nom — فَعَل`,root:`س ن د`},
      {w:`سَهْم`,p:`سهم`,tr:`sahm`,fr:`action (bourse) (pl. أَسْهُم)`,fm:`Nom — فَعْل`,root:`س ه م`},
      {w:`بُورْصَة`,p:`بورصة`,tr:`būrṣa`,fr:`bourse des valeurs`,fm:`Nom (emprunt)`,root:`—`},
      {w:`تَصْدِير`,p:`تصدير`,tr:`taṣdīr`,fr:`exportation`,fm:`Masdar Form II`,root:`ص د ر`},
      {w:`اسْتِيرَاد`,p:`استيراد`,tr:`istīrād`,fr:`importation`,fm:`Masdar Form X`,root:`و ر د`},
      {w:`مِيزَان التِّجَارَة`,p:`ميزان التجارة`,tr:`mīzān at-tijāra`,fr:`balance commerciale`,fm:`Idāfa`,root:`و ز ن`},
      {w:`تَنَافُسِيَّة`,p:`تنافسية`,tr:`tanāfusiyya`,fr:`compétitivité`,fm:`Nisba de تنافس`,root:`ن ف س`},
      {w:`رَأْسُ الْمَال`,p:`رأس المال`,tr:`raʾs al-māl`,fr:`capital`,fm:`Idāfa`,root:`ر أ س`},
      {w:`دَيْن`,p:`دين`,tr:`dayn`,fr:`dette (pl. دُيُون)`,fm:`Nom — فَعْل`,root:`د ي ن`},
      {w:`قَرْض`,p:`قرض`,tr:`qarḍ`,fr:`prêt, crédit (pl. قُرُوض)`,fm:`Masdar Form I`,root:`ق ر ض`},
      {w:`فَائِدَة`,p:`فائدة`,tr:`fāʾida`,fr:`intérêt (financier), avantage`,fm:`Participe actif fém. Form I`,root:`ف ي د`},
      {w:`سِعْر الصَّرْف`,p:`سعر الصرف`,tr:`siʿr aṣ-ṣarf`,fr:`taux de change`,fm:`Idāfa`,root:`ص ر ف`},
      {w:`تَضَخُّم مَالِيّ`,p:`تضخم مالي`,tr:`taḍakhkhum mālī`,fr:`inflation monétaire`,fm:`Syntagme`,root:`ض خ م`}
    ]
  },
  {
    theme:`السِّيَاسَةُ وَالْحُكْمُ — Politique et gouvernance`,
    words:[
      {w:`دِيمُقْرَاطِيَّة`,p:`ديمقراطية`,tr:`dīmuqrāṭiyya`,fr:`démocratie`,fm:`Nom (emprunt)`,root:`—`},
      {w:`دِكْتَاتُورِيَّة`,p:`ديكتاتورية`,tr:`diktātūriyya`,fr:`dictature`,fm:`Nom (emprunt)`,root:`—`},
      {w:`جُمْهُورِيَّة`,p:`جمهورية`,tr:`jumhūriyya`,fr:`république`,fm:`Nisba de جُمْهُور`,root:`ج م ه`},
      {w:`مَمْلَكَة`,p:`مملكة`,tr:`mamlaka`,fr:`royaume`,fm:`Nom — مَفْعَلَة`,root:`م ل ك`},
      {w:`رَئِيس`,p:`رئيس`,tr:`raʾīs`,fr:`président, chef (pl. رُؤَسَاء)`,fm:`Nom — فَعِيل`,root:`ر أ س`},
      {w:`وَزِير`,p:`وزير`,tr:`wazīr`,fr:`ministre (pl. وُزَرَاء)`,fm:`Nom — فَعِيل`,root:`و ز ر`},
      {w:`بُرْلَمَان`,p:`برلمان`,tr:`burlumān`,fr:`parlement`,fm:`Nom (emprunt)`,root:`—`},
      {w:`انْتِخَابَات`,p:`انتخابات`,tr:`intikābāt`,fr:`élections`,fm:`Pl. de انتخاب`,root:`ن خ ب`},
      {w:`حِزْب`,p:`حزب`,tr:`ḥizb`,fr:`parti politique (pl. أَحْزَاب)`,fm:`Nom — فِعْل`,root:`ح ز ب`},
      {w:`مُعَارَضَة`,p:`معارضة`,tr:`muʿāraḍa`,fr:`opposition politique`,fm:`Masdar Form III`,root:`ع ر ض`},
      {w:`حُكُومَة`,p:`حكومة`,tr:`ḥukūma`,fr:`gouvernement`,fm:`Masdar Form II`,root:`ح ك م`},
      {w:`وَزَارَة`,p:`وزارة`,tr:`wizāra`,fr:`ministère`,fm:`Masdar Form I`,root:`و ز ر`},
      {w:`سِيَاسَة`,p:`سياسة`,tr:`siyāsa`,fr:`politique (art de gouverner)`,fm:`Masdar Form I`,root:`س ي س`},
      {w:`دِبْلُومَاسِيَّة`,p:`دبلوماسية`,tr:`diblūmāsiyya`,fr:`diplomatie`,fm:`Nom (emprunt)`,root:`—`},
      {w:`سَفِير`,p:`سفير`,tr:`safīr`,fr:`ambassadeur`,fm:`Nom — فَعِيل`,root:`س ف ر`},
      {w:`مُعَاهَدَة`,p:`معاهدة`,tr:`muʿāhada`,fr:`traité, accord international`,fm:`Masdar Form III`,root:`ع ه د`},
      {w:`اتِّفَاقِيَّة`,p:`اتفاقية`,tr:`ittifāqiyya`,fr:`convention, accord`,fm:`Nisba de اتفاق`,root:`و ف ق`},
      {w:`أَمَن`,p:`أمن`,tr:`aman`,fr:`sécurité, sûreté`,fm:`Masdar Form I`,root:`أ م ن`},
      {w:`جَيْش`,p:`جيش`,tr:`jaysh`,fr:`armée (pl. جُيُوش)`,fm:`Nom — فَعْل`,root:`ج ي ش`},
      {w:`قُوَّات`,p:`قوات`,tr:`quwwāt`,fr:`forces (armées) (pl. de قُوَّة)`,fm:`Pl. de قُوَّة`,root:`ق و ي`},
      {w:`سِيَادَة`,p:`سيادة`,tr:`siyāda`,fr:`souveraineté`,fm:`Masdar Form I`,root:`س و د`},
      {w:`اسْتِقْلَال`,p:`استقلال`,tr:`istiqlāl`,fr:`indépendance`,fm:`Masdar Form X`,root:`ق ل ل`},
      {w:`وَحْدَة`,p:`وحدة`,tr:`waḥda`,fr:`unité, union`,fm:`Masdar Form I`,root:`و ح د`},
      {w:`فَدَرَالِيَّة`,p:`فدرالية`,tr:`fadarāliyya`,fr:`fédéralisme`,fm:`Nom (emprunt)`,root:`—`},
      {w:`إِدَارَة`,p:`إدارة`,tr:`idāra`,fr:`administration, gestion`,fm:`Masdar Form IV`,root:`د و ر`},
      {w:`فَسَاد`,p:`فساد`,tr:`fasād`,fr:`corruption`,fm:`Masdar Form I`,root:`ف س د`},
      {w:`شَفَافِيَّة`,p:`شفافية`,tr:`shafāfiyya`,fr:`transparence`,fm:`Nisba de شفاف`,root:`ش ف ف`},
      {w:`مُحَاسَبَة`,p:`محاسبة`,tr:`muḥāsaba`,fr:`reddition de comptes`,fm:`Masdar Form III`,root:`ح س ب`},
      {w:`لَامَرْكَزِيَّة`,p:`لامركزية`,tr:`lāmarkaziyya`,fr:`décentralisation`,fm:`Nisba`,root:`م ر ك`},
      {w:`حَوْكَمَة`,p:`حوكمة`,tr:`ḥawkama`,fr:`gouvernance`,fm:`Masdar (néologisme)`,root:`ح ك م`},
      {w:`مَجْلِس`,p:`مجلس`,tr:`majlis`,fr:`conseil, assemblée (pl. مَجَالِس)`,fm:`Nom de lieu Form I`,root:`ج ل س`},
      {w:`لَجْنَة`,p:`لجنة`,tr:`lajna`,fr:`comité, commission`,fm:`Nom — فَعْلَة`,root:`ل ج ن`},
      {w:`تَمْثِيل`,p:`تمثيل`,tr:`tamthīl`,fr:`représentation`,fm:`Masdar Form II`,root:`م ث ل`},
      {w:`حَمَلَة`,p:`حملة`,tr:`ḥamala`,fr:`campagne (électorale)`,fm:`Nom — فَعَلَة`,root:`ح م ل`},
      {w:`مَرْسُوم`,p:`مرسوم`,tr:`marsūm`,fr:`décret`,fm:`Participe passif Form I`,root:`ر س م`}
    ]
  },
  {
    theme:`الإِعْلَامُ وَالتَّوَاصُلُ — Médias et communication`,
    words:[
      {w:`صَحِيفَة`,p:`صحيفة`,tr:`ṣaḥīfa`,fr:`journal, quotidien (pl. صُحُف)`,fm:`Nom — فَعِيلَة`,root:`ص ح ف`},
      {w:`مَجَلَّة`,p:`مجلة`,tr:`majalla`,fr:`magazine, revue`,fm:`Nom — géminé`,root:`ج ل ل`},
      {w:`قَنَاة`,p:`قناة`,tr:`qanāh`,fr:`chaîne (TV), canal`,fm:`Nom — فَعَالَة`,root:`ق ن و`},
      {w:`إِذَاعَة`,p:`إذاعة`,tr:`idhāʿa`,fr:`radio, diffusion`,fm:`Masdar Form IV`,root:`ذ و ع`},
      {w:`إِعْلَان`,p:`إعلان`,tr:`iʿlān`,fr:`annonce, publicité`,fm:`Masdar Form IV`,root:`ع ل ن`},
      {w:`مَقَالَة`,p:`مقالة`,tr:`maqāla`,fr:`article (de presse)`,fm:`Nom — مَفْعَلَة`,root:`ق و ل`},
      {w:`تَحْقِيق`,p:`تحقيق`,tr:`taḥqīq`,fr:`enquête, reportage`,fm:`Masdar Form II`,root:`ح ق ق`},
      {w:`خَبَر`,p:`خبر`,tr:`khabar`,fr:`nouvelle, info (pl. أَخْبَار)`,fm:`Nom — فَعَل`,root:`خ ب ر`},
      {w:`نَشْرَة`,p:`نشرة`,tr:`nashra`,fr:`bulletin d'information`,fm:`Nom — فَعْلَة`,root:`ن ش ر`},
      {w:`مُرَاسِل`,p:`مراسل`,tr:`murāsil`,fr:`correspondant (journaliste)`,fm:`Participe actif Form III`,root:`ر س ل`},
      {w:`مُحَرِّر`,p:`محرر`,tr:`muḥarrir`,fr:`rédacteur, éditeur`,fm:`Participe actif Form II`,root:`ح ر ر`},
      {w:`رَئِيس تَحْرِير`,p:`رئيس تحرير`,tr:`raʾīs taḥrīr`,fr:`rédacteur en chef`,fm:`Idāfa`,root:`ح ر ر`},
      {w:`صِحَافَة`,p:`صحافة`,tr:`ṣiḥāfa`,fr:`journalisme, presse`,fm:`Nom — فِعَالَة`,root:`ص ح ف`},
      {w:`حُرِّيَّة الصَّحَافَة`,p:`حرية الصحافة`,tr:`ḥurriyyat aṣ-ṣiḥāfa`,fr:`liberté de la presse`,fm:`Idāfa`,root:`ص ح ف`},
      {w:`وَسِيلَة إِعْلَام`,p:`وسيلة إعلام`,tr:`wasīlat iʿlām`,fr:`organe médiatique`,fm:`Idāfa`,root:`و س ل`},
      {w:`شَبَكَة اجْتِمَاعِيَّة`,p:`شبكة اجتماعية`,tr:`shabaka ijtimāʿiyya`,fr:`réseau social`,fm:`Syntagme`,root:`ش ب ك`},
      {w:`مُتَابِع`,p:`متابع`,tr:`mutābiʿ`,fr:`abonné, suiveur`,fm:`Participe actif Form III`,root:`ت ب ع`},
      {w:`مَحْتَوَى`,p:`محتوى`,tr:`maḥtawā`,fr:`contenu (digital)`,fm:`Participe passif Form VIII`,root:`ح و ي`},
      {w:`مُؤَثِّر`,p:`مؤثر`,tr:`muʾaththir`,fr:`influenceur`,fm:`Participe actif Form II`,root:`أ ث ر`},
      {w:`ثَقَافَة رَقْمِيَّة`,p:`ثقافة رقمية`,tr:`thaqāfa raqmiyya`,fr:`culture numérique`,fm:`Syntagme`,root:`ث ق ف`},
      {w:`قَرْصَنَة`,p:`قرصنة`,tr:`qurṣana`,fr:`piratage informatique`,fm:`Nom — فَعْلَنَة`,root:`ق ر ص`},
      {w:`خُصُوصِيَّة`,p:`خصوصية`,tr:`khuṣūṣiyya`,fr:`vie privée, confidentialité`,fm:`Nisba de خُصُوص`,root:`خ ص ص`},
      {w:`بَيَانَات شَخْصِيَّة`,p:`بيانات شخصية`,tr:`bayānāt shakhṣiyya`,fr:`données personnelles`,fm:`Syntagme`,root:`ب ي ن`},
      {w:`تَدَفُّق`,p:`تدفق`,tr:`tadaffuq`,fr:`flux, débit, streaming`,fm:`Masdar Form V`,root:`د ف ق`},
      {w:`بَثّ مُبَاشِر`,p:`بث مباشر`,tr:`bathth mubāshir`,fr:`direct, live`,fm:`Syntagme`,root:`ب ث ث`},
      {w:`خَبَر كَاذِب`,p:`خبر كاذب`,tr:`khabar kādhib`,fr:`fausse information, fake news`,fm:`Syntagme`,root:`ك ذ ب`},
      {w:`تَدْقِيق`,p:`تدقيق`,tr:`tadqīq`,fr:`fact-checking, vérification`,fm:`Masdar Form II`,root:`د ق ق`},
      {w:`تَصْفِيَة`,p:`تصفية`,tr:`taṣfiya`,fr:`filtrage, modération`,fm:`Masdar Form II`,root:`ص ف و`},
      {w:`حَجْب`,p:`حجب`,tr:`ḥajb`,fr:`blocage, censure`,fm:`Masdar Form I`,root:`ح ج ب`},
      {w:`مِنَصَّة`,p:`منصة`,tr:`minaṣṣa`,fr:`plateforme numérique`,fm:`Nom — مِفْعَلَة`,root:`ن ص ص`}
    ]
  },
  {
    theme:`الْعُلُومُ وَالتِّقَنِيَّةُ — Sciences et technologie`,
    words:[
      {w:`فِيزْيَاء`,p:`فيزياء`,tr:`fīzyāʾ`,fr:`physique`,fm:`Nom (emprunt grec)`,root:`—`},
      {w:`كِيمْيَاء`,p:`كيمياء`,tr:`kīmyāʾ`,fr:`chimie`,fm:`Nom (emprunt arabe → grec)`,root:`—`},
      {w:`أَحْيَاء`,p:`أحياء`,tr:`aḥyāʾ`,fr:`biologie`,fm:`Pl. de حَيّ`,root:`ح ي ي`},
      {w:`رِيَاضِيَّات`,p:`رياضيات`,tr:`riyāḍiyyāt`,fr:`mathématiques`,fm:`Pl. de رياضية`,root:`ر و ض`},
      {w:`جِيُولُوجِيَّا`,p:`جيولوجيا`,tr:`jiyūlūjiyā`,fr:`géologie`,fm:`Nom (emprunt)`,root:`—`},
      {w:`فَلَك`,p:`فلك`,tr:`falak`,fr:`astronomie, orbite`,fm:`Nom — فَعَل`,root:`ف ل ك`},
      {w:`طَاقَة`,p:`طاقة`,tr:`ṭāqa`,fr:`énergie`,fm:`Nom — فَاعِلَة`,root:`ط و ق`},
      {w:`طَاقَة شَمْسِيَّة`,p:`طاقة شمسية`,tr:`ṭāqa shamsiyya`,fr:`énergie solaire`,fm:`Syntagme`,root:`ش م س`},
      {w:`طَاقَة نَوَوِيَّة`,p:`طاقة نووية`,tr:`ṭāqa nawawiyya`,fr:`énergie nucléaire`,fm:`Syntagme`,root:`ن و و`},
      {w:`كَهْرَبَاء`,p:`كهرباء`,tr:`kahrabāʾ`,fr:`électricité`,fm:`Nom (emprunt)`,root:`—`},
      {w:`مَغْنَاطِيس`,p:`مغناطيس`,tr:`maghnaṭīs`,fr:`aimant, magnétisme`,fm:`Nom (emprunt grec)`,root:`—`},
      {w:`تَجْرِبَة`,p:`تجربة`,tr:`tajriba`,fr:`expérience, test (pl. تَجَارِب)`,fm:`Nom — تَفْعِلَة`,root:`ج ر ب`},
      {w:`مُخْتَبَر`,p:`مختبر`,tr:`mukhtabar`,fr:`laboratoire`,fm:`Participe passif Form VIII`,root:`خ ب ر`},
      {w:`مِجْهَر`,p:`مجهر`,tr:`mijhar`,fr:`microscope`,fm:`Nom — مِفْعَل`,root:`ج ه ر`},
      {w:`تَلِسْكُوب`,p:`تلسكوب`,tr:`taliskūb`,fr:`télescope`,fm:`Nom (emprunt)`,root:`—`},
      {w:`اكْتِشَاف`,p:`اكتشاف`,tr:`iktishāf`,fr:`découverte`,fm:`Masdar Form VIII`,root:`ك ش ف`},
      {w:`اخْتِرَاع`,p:`اختراع`,tr:`ikhtirāʿ`,fr:`invention`,fm:`Masdar Form VIII`,root:`خ ر ع`},
      {w:`بَحْث عِلْمِيّ`,p:`بحث علمي`,tr:`baḥth ʿilmī`,fr:`recherche scientifique`,fm:`Syntagme`,root:`ب ح ث`},
      {w:`نَظَرِيَّة`,p:`نظرية`,tr:`naẓariyya`,fr:`théorie`,fm:`Nisba de نَظَر`,root:`ن ظ ر`},
      {w:`فَرْضِيَّة`,p:`فرضية`,tr:`farḍiyya`,fr:`hypothèse`,fm:`Nisba de فَرْض`,root:`ف ر ض`},
      {w:`دَلِيل`,p:`دليل`,tr:`dalīl`,fr:`preuve, indice (pl. أَدِلَّة)`,fm:`Nom — فَعِيل`,root:`د ل ل`},
      {w:`ذَكَاء اصْطِنَاعِيّ`,p:`ذكاء اصطناعي`,tr:`dhakāʾ iṣṭināʿī`,fr:`intelligence artificielle`,fm:`Syntagme`,root:`ذ ك و`},
      {w:`تَعَلُّم آلِيّ`,p:`تعلم آلي`,tr:`taʿallum ālī`,fr:`apprentissage automatique`,fm:`Syntagme`,root:`ع ل م`},
      {w:`بَرْمَجَة`,p:`برمجة`,tr:`barmaja`,fr:`programmation`,fm:`Masdar (quadrilitère)`,root:`ب ر م`},
      {w:`رُوبُوت`,p:`روبوت`,tr:`rūbūt`,fr:`robot`,fm:`Nom (emprunt)`,root:`—`},
      {w:`نَانُو تِقَنِيَّة`,p:`نانو تقنية`,tr:`nānū tiqniyya`,fr:`nanotechnologie`,fm:`Syntagme`,root:`—`},
      {w:`هَنْدَسَة`,p:`هندسة`,tr:`handasa`,fr:`ingénierie, géométrie`,fm:`Nom (emprunt)`,root:`ه ن د`},
      {w:`طِبّ`,p:`طب`,tr:`ṭibb`,fr:`médecine (discipline)`,fm:`Masdar Form I — géminé`,root:`ط ب ب`},
      {w:`صَيْدَلَة`,p:`صيدلة`,tr:`ṣaydala`,fr:`pharmacie (discipline)`,fm:`Nom`,root:`ص ي د`},
      {w:`بِيُولُوجِيَّا جُزَيْئِيَّة`,p:`بيولوجيا جزيئية`,tr:`biyūlūjiyā juzayʾiyya`,fr:`biologie moléculaire`,fm:`Syntagme`,root:`—`}
    ]
  },
  {
    theme:`الْبِيئَةُ وَالاسْتِدَامَةُ — Environnement et durabilité`,
    words:[
      {w:`تَغَيُّر مَنَاخِيّ`,p:`تغير مناخي`,tr:`taghayur manākhī`,fr:`changement climatique`,fm:`Syntagme`,root:`غ ي ر`},
      {w:`احْتِبَاس حَرَارِيّ`,p:`احتباس حراري`,tr:`iḥtibās ḥarārī`,fr:`réchauffement climatique`,fm:`Syntagme`,root:`ح ب س`},
      {w:`غَازَات الدَّفِيئَة`,p:`غازات الدفيئة`,tr:`ghāzāt ad-dafīʾa`,fr:`gaz à effet de serre`,fm:`Syntagme`,root:`د ف أ`},
      {w:`انْبِعَاثَات`,p:`انبعاثات`,tr:`inbiʿāthāt`,fr:`émissions (de CO₂)`,fm:`Pl. de انبعاث`,root:`ب ع ث`},
      {w:`تَلَوُّث`,p:`تلوث`,tr:`talawwuth`,fr:`pollution`,fm:`Masdar Form V`,root:`ل و ث`},
      {w:`تَلَوُّث الْهَوَاء`,p:`تلوث الهواء`,tr:`talawwuth al-hawāʾ`,fr:`pollution de l'air`,fm:`Idāfa`,root:`ه و أ`},
      {w:`نَفَايَات`,p:`نفايات`,tr:`nafāyāt`,fr:`déchets`,fm:`Pl. de نَفَايَة`,root:`ن ف ي`},
      {w:`إِعَادَة تَدْوِير`,p:`إعادة تدوير`,tr:`iʿādat tadwīr`,fr:`recyclage`,fm:`Masdar Form IV`,root:`د و ر`},
      {w:`طَاقَة مُتَجَدِّدَة`,p:`طاقة متجددة`,tr:`ṭāqa mutajaddida`,fr:`énergie renouvelable`,fm:`Syntagme`,root:`ج د د`},
      {w:`تَنَوُّع بِيُولُوجِيّ`,p:`تنوع بيولوجي`,tr:`tanawwuʿ biyūlūjī`,fr:`biodiversité`,fm:`Syntagme`,root:`ن و ع`},
      {w:`انْقِرَاض`,p:`انقراض`,tr:`inqirāḍ`,fr:`extinction (d'espèces)`,fm:`Masdar Form VII`,root:`ق ر ض`},
      {w:`إِزَالَة الْغَابَات`,p:`إزالة الغابات`,tr:`izālat al-ghābāt`,fr:`déforestation`,fm:`Idāfa`,root:`غ ي ب`},
      {w:`تَصَحُّر`,p:`تصحر`,tr:`taṣaḥḥur`,fr:`désertification`,fm:`Masdar Form V`,root:`ص ح ر`},
      {w:`حِمَايَة الْبِيئَة`,p:`حماية البيئة`,tr:`ḥimāyat al-bīʾa`,fr:`protection de l'environnement`,fm:`Idāfa`,root:`ب و أ`},
      {w:`أَحْفُورِيَّات`,p:`أحفوريات`,tr:`aḥfūriyyāt`,fr:`combustibles fossiles`,fm:`Pl. nisba`,root:`ح ف ر`},
      {w:`كَرْبُون`,p:`كربون`,tr:`karbūn`,fr:`carbone`,fm:`Nom (emprunt)`,root:`—`},
      {w:`طَبَقَة الأُوزُون`,p:`طبقة الأوزون`,tr:`ṭabaqat al-ūzūn`,fr:`couche d'ozone`,fm:`Idāfa`,root:`ط ب ق`},
      {w:`فَيَضَانَات`,p:`فيضانات`,tr:`fayaḍānāt`,fr:`inondations`,fm:`Pl. de فيضان`,root:`ف ي ض`},
      {w:`جَفَاف`,p:`جفاف`,tr:`jafāf`,fr:`sécheresse`,fm:`Masdar Form I — géminé`,root:`ج ف ف`},
      {w:`عَاصِفَة`,p:`عاصفة`,tr:`ʿāṣifa`,fr:`tempête, ouragan`,fm:`Participe actif fém.`,root:`ع ص ف`},
      {w:`أَمَانَة الأَرْض`,p:`أمانة الأرض`,tr:`amānat al-arḍ`,fr:`responsabilité envers la terre`,fm:`Idāfa`,root:`أ م ن`},
      {w:`اسْتِدَامَة`,p:`استدامة`,tr:`istidāma`,fr:`durabilité`,fm:`Masdar Form X`,root:`د و م`},
      {w:`بَصْمَة كَرْبُونِيَّة`,p:`بصمة كربونية`,tr:`baṣma karbūniyya`,fr:`empreinte carbone`,fm:`Syntagme`,root:`ب ص م`},
      {w:`اقْتِصَاد أَخْضَر`,p:`اقتصاد أخضر`,tr:`iqtiṣād akhḍar`,fr:`économie verte`,fm:`Syntagme`,root:`خ ض ر`},
      {w:`مُجْتَمَع مُسْتَدَام`,p:`مجتمع مستدام`,tr:`mujtamaʿ mustadām`,fr:`société durable`,fm:`Syntagme`,root:`د و م`},
      {w:`زِرَاعَة مُسْتَدَامَة`,p:`زراعة مستدامة`,tr:`zirāʿa mustadāma`,fr:`agriculture durable`,fm:`Syntagme`,root:`ز ر ع`},
      {w:`مِيَاه نَظِيفَة`,p:`مياه نظيفة`,tr:`miyāh naẓīfa`,fr:`eau propre, eau potable`,fm:`Syntagme`,root:`م و ه`},
      {w:`تَدَهْوُر بِيئِيّ`,p:`تدهور بيئي`,tr:`tadahwur bīʾī`,fr:`dégradation environnementale`,fm:`Syntagme`,root:`ه و ر`},
      {w:`سِيَاسَة بِيئِيَّة`,p:`سياسة بيئية`,tr:`siyāsa bīʾiyya`,fr:`politique environnementale`,fm:`Syntagme`,root:`ب و أ`},
      {w:`تَنْمِيَة مُسْتَدَامَة`,p:`تنمية مستدامة`,tr:`tanmiya mustadāma`,fr:`développement durable`,fm:`Syntagme`,root:`ن م و`}
    ]
  },
  {
    theme:`الأَدَبُ وَالثَّقَافَةُ — Littérature et culture`,
    words:[
      {w:`شِعْر`,p:`شعر`,tr:`shiʿr`,fr:`poésie`,fm:`Masdar Form I`,root:`ش ع ر`},
      {w:`نَثْر`,p:`نثر`,tr:`nathr`,fr:`prose`,fm:`Masdar Form I`,root:`ن ث ر`},
      {w:`قِصَّة`,p:`قصة`,tr:`qiṣṣa`,fr:`histoire, conte (pl. قِصَص)`,fm:`Nom — géminé`,root:`ق ص ص`},
      {w:`رِوَايَة`,p:`رواية`,tr:`riwāya`,fr:`roman, récit`,fm:`Masdar Form I`,root:`ر و ي`},
      {w:`مَسْرَحِيَّة`,p:`مسرحية`,tr:`masraḥiyya`,fr:`pièce de théâtre`,fm:`Nisba de مسرح`,root:`س ر ح`},
      {w:`بَطَل`,p:`بطل`,tr:`baṭal`,fr:`héros, protagoniste`,fm:`Nom — فَعَل`,root:`ب ط ل`},
      {w:`شَخْصِيَّة`,p:`شخصية`,tr:`shakhṣiyya`,fr:`personnage, personnalité`,fm:`Nisba`,root:`ش خ ص`},
      {w:`حَبْكَة`,p:`حبكة`,tr:`ḥabka`,fr:`intrigue (littéraire)`,fm:`Nom — فَعْلَة`,root:`ح ب ك`},
      {w:`سَرْد`,p:`سرد`,tr:`sard`,fr:`narration, récit`,fm:`Masdar Form I`,root:`س ر د`},
      {w:`رَاوٍ`,p:`راوٍ`,tr:`rāwin`,fr:`narrateur, conteur`,fm:`Participe actif Form I — défectueux`,root:`ر و ي`},
      {w:`أُسْلُوب`,p:`أسلوب`,tr:`uslūb`,fr:`style littéraire (pl. أَسَالِيب)`,fm:`Nom — أُفْعُول`,root:`س ل ب`},
      {w:`لُغَة`,p:`لغة`,tr:`lugha`,fr:`langue, langage (pl. لُغَات)`,fm:`Nom — لُفَعَة`,root:`ل غ و`},
      {w:`مُعْجَم`,p:`معجم`,tr:`muʿjam`,fr:`lexique, dictionnaire`,fm:`Participe passif Form IV`,root:`ع ج م`},
      {w:`قَافِيَة`,p:`قافية`,tr:`qāfiya`,fr:`rime`,fm:`Nom — فَاعِلَة`,root:`ق ف و`},
      {w:`وَزْن`,p:`وزن`,tr:`wazn`,fr:`mètre poétique, poids`,fm:`Masdar Form I`,root:`و ز ن`},
      {w:`صُورَة أَدَبِيَّة`,p:`صورة أدبية`,tr:`ṣūra adabiyya`,fr:`image littéraire, figure de style`,fm:`Syntagme`,root:`ص و ر`},
      {w:`اسْتِعَارَة`,p:`استعارة`,tr:`istiʿāra`,fr:`métaphore`,fm:`Masdar Form X`,root:`ع ي ر`},
      {w:`تَشْبِيه`,p:`تشبيه`,tr:`tashbīh`,fr:`comparaison, simile`,fm:`Masdar Form II`,root:`ش ب ه`},
      {w:`كِنَايَة`,p:`كناية`,tr:`kināya`,fr:`allusion, métonymie`,fm:`Masdar Form I`,root:`ك ن و`},
      {w:`طِبَاق`,p:`طباق`,tr:`ṭibāq`,fr:`antithèse`,fm:`Masdar Form III`,root:`ط ب ق`},
      {w:`تُرَاث`,p:`تراث`,tr:`turāth`,fr:`patrimoine, héritage culturel`,fm:`Masdar Form I`,root:`و ر ث`},
      {w:`فُنُون`,p:`فنون`,tr:`funūn`,fr:`arts (pl. de فَنّ)`,fm:`Pl. بَعْل`,root:`ف ن ن`},
      {w:`مُوسِيقِيّ`,p:`موسيقي`,tr:`mūsīqī`,fr:`musical, musicien`,fm:`Nisba de مُوسِيقَى`,root:`—`},
      {w:`رِسَالَة`,p:`رسالة`,tr:`risāla`,fr:`message, épître`,fm:`Nom — فِعَالَة`,root:`ر س ل`},
      {w:`نَقْد`,p:`نقد`,tr:`naqd`,fr:`critique (littéraire)`,fm:`Masdar Form I`,root:`ن ق د`},
      {w:`حَضَارَة`,p:`حضارة`,tr:`ḥaḍāra`,fr:`civilisation`,fm:`Masdar Form I`,root:`ح ض ر`},
      {w:`تُرَاثِيّ`,p:`تراثي`,tr:`turāthī`,fr:`patrimonial, classique`,fm:`Nisba`,root:`و ر ث`},
      {w:`مُوَرِّث`,p:`مورث`,tr:`muwarrith`,fr:`qui lègue, transmis`,fm:`Participe actif Form II`,root:`و ر ث`},
      {w:`حِكَايَة`,p:`حكاية`,tr:`ḥikāya`,fr:`conte, récit, narration`,fm:`Masdar Form I`,root:`ح ك ي`},
      {w:`أَسْطُورَة`,p:`أسطورة`,tr:`usṭūra`,fr:`mythe, légende`,fm:`Nom (emprunt)`,root:`—`}
    ]
  },
  {
    theme:`التَّارِيخُ وَالْحَضَارَةُ الإِسْلَامِيَّةُ — Histoire islamique`,
    words:[
      {w:`صَحَابِيّ`,p:`صحابي`,tr:`ṣaḥābī`,fr:`Compagnon du Prophète`,fm:`Nisba de صَحَابَة`,root:`ص ح ب`},
      {w:`تَابِعِيّ`,p:`تابعي`,tr:`tābiʿī`,fr:`successeur des Compagnons`,fm:`Nisba de تَابِع`,root:`ت ب ع`},
      {w:`خِلَافَة`,p:`خلافة`,tr:`khilāfa`,fr:`califat`,fm:`Masdar Form I`,root:`خ ل ف`},
      {w:`خَلِيفَة`,p:`خليفة`,tr:`khalīfa`,fr:`calife (pl. خُلَفَاء)`,fm:`Nom — فَعِيلَة`,root:`خ ل ف`},
      {w:`فُتُوحَات`,p:`فتوحات`,tr:`futūḥāt`,fr:`conquêtes islamiques`,fm:`Pl. de فَتْح`,root:`ف ت ح`},
      {w:`أُمَوِيّ`,p:`أموي`,tr:`umawī`,fr:`omeyyade`,fm:`Nisba de أُمَيَّة`,root:`—`},
      {w:`عَبَّاسِيّ`,p:`عباسي`,tr:`ʿabbāsī`,fr:`abbasside`,fm:`Nisba`,root:`ع ب س`},
      {w:`فَاطِمِيّ`,p:`فاطمي`,tr:`fāṭimī`,fr:`fatimide`,fm:`Nisba de فاطمة`,root:`—`},
      {w:`عُثْمَانِيّ`,p:`عثماني`,tr:`ʿuthmānī`,fr:`ottoman`,fm:`Nisba de عُثْمَان`,root:`ع ث م`},
      {w:`دَيْر`,p:`دير`,tr:`dayr`,fr:`monastère (pl. أَدْيَرَة)`,fm:`Nom`,root:`د ي ر`},
      {w:`مَدْرَسَة`,p:`مدرسة`,tr:`madrasa`,fr:`école coranique, médersa`,fm:`Nom de lieu`,root:`د ر س`},
      {w:`بَيْت الْحِكْمَة`,p:`بيت الحكمة`,tr:`bayt al-ḥikma`,fr:`Maison de la Sagesse (Bagdad)`,fm:`Idāfa`,root:`ح ك م`},
      {w:`تَرْجَمَة`,p:`ترجمة`,tr:`tarjama`,fr:`traduction (mouvement de ~)`,fm:`Masdar quadrilitère`,root:`—`},
      {w:`نَهْضَة`,p:`نهضة`,tr:`nahḍa`,fr:`renaissance, réveil`,fm:`Masdar Form I`,root:`ن ه ض`},
      {w:`حُرُوب الصَّلِيبِيَّة`,p:`حروب الصليبية`,tr:`ḥurūb aṣ-ṣalībiyya`,fr:`Croisades`,fm:`Syntagme`,root:`ص ل ب`},
      {w:`مَوْقِعَة`,p:`موقعة`,tr:`mawqiʿa`,fr:`bataille, engagement militaire`,fm:`Nom de lieu Form I`,root:`و ق ع`},
      {w:`غَزْوَة`,p:`غزوة`,tr:`ghazwa`,fr:`expédition (du Prophète)`,fm:`Nom — فَعْلَة`,root:`غ ز و`},
      {w:`هِجْرَة`,p:`هجرة`,tr:`hijra`,fr:`Hégire, émigration`,fm:`Masdar Form I`,root:`ه ج ر`},
      {w:`فَتْح مَكَّة`,p:`فتح مكة`,tr:`fatḥ makka`,fr:`conquête de La Mecque`,fm:`Syntagme historique`,root:`ف ت ح`},
      {w:`قُرَيْش`,p:`قريش`,tr:`quraysh`,fr:`Quraysh (tribu du Prophète)`,fm:`Nom propre`,root:`ق ر ش`},
      {w:`أَنْصَار`,p:`أنصار`,tr:`anṣār`,fr:`Ansars (Médinois qui aidèrent)`,fm:`Pl. de نَاصِر`,root:`ن ص ر`},
      {w:`مُهَاجِرُون`,p:`مهاجرون`,tr:`muhājirūn`,fr:`Muhajiruns (Mecquois émigrés)`,fm:`Pl. de مُهَاجِر`,root:`ه ج ر`},
      {w:`سِيرَة نَبَوِيَّة`,p:`سيرة نبوية`,tr:`sīra nabawiyya`,fr:`biographie du Prophète`,fm:`Syntagme`,root:`س ي ر`},
      {w:`مَغَازِي`,p:`مغازي`,tr:`maghāzī`,fr:`épopées militaires (du Prophète)`,fm:`Pl. de مَغْزَاة`,root:`غ ز و`},
      {w:`إِسْلَام مُبَكِّر`,p:`إسلام مبكر`,tr:`islām mubakkir`,fr:`islam primitif, des débuts`,fm:`Syntagme`,root:`ب ك ر`},
      {w:`دَوْلَة إِسْلَامِيَّة`,p:`دولة إسلامية`,tr:`dawla islāmiyya`,fr:`État islamique (historique)`,fm:`Syntagme`,root:`د و ل`},
      {w:`زَعِيم`,p:`زعيم`,tr:`zaʿīm`,fr:`chef, leader (pl. زُعَمَاء)`,fm:`Nom — فَعِيل`,root:`ز ع م`},
      {w:`حَاكِم`,p:`حاكم`,tr:`ḥākim`,fr:`gouvernant, souverain`,fm:`Participe actif Form I`,root:`ح ك م`},
      {w:`أَمِير`,p:`أمير`,tr:`amīr`,fr:`émir, prince (pl. أُمَرَاء)`,fm:`Nom — فَعِيل`,root:`أ م ر`},
      {w:`وَزِير`,p:`وزير`,tr:`wazīr`,fr:`vizir, ministre (pl. وُزَرَاء)`,fm:`Nom — فَعِيل`,root:`و ز ر`}
    ]
  },
  {
    theme:`الدِّينُ الإِسْلَامِيُّ — مُتَقَدِّم — Islam approfondi`,
    words:[
      {w:`تَوْحِيد`,p:`توحيد`,tr:`tawḥīd`,fr:`unicité divine (monothéisme)`,fm:`Masdar Form II`,root:`و ح د`},
      {w:`أُصُول الدِّين`,p:`أصول الدين`,tr:`uṣūl ad-dīn`,fr:`fondements de la foi`,fm:`Idāfa`,root:`أ ص ل`},
      {w:`أَرْكَان الإِيمَان`,p:`أركان الإيمان`,tr:`arkān al-īmān`,fr:`piliers de la foi`,fm:`Idāfa`,root:`ر ك ن`},
      {w:`كُفْر`,p:`كفر`,tr:`kufr`,fr:`mécréance, ingratitude`,fm:`Masdar Form I`,root:`ك ف ر`},
      {w:`شِرْك`,p:`شرك`,tr:`shirk`,fr:`polythéisme, associationnisme`,fm:`Masdar Form I`,root:`ش ر ك`},
      {w:`نِفَاق`,p:`نفاق`,tr:`nifāq`,fr:`hypocrisie`,fm:`Masdar Form I`,root:`ن ف ق`},
      {w:`تَقْوَى`,p:`تقوى`,tr:`taqwā`,fr:`piété, crainte de Dieu`,fm:`Masdar Form I — défectueux`,root:`و ق ي`},
      {w:`وَرَع`,p:`ورع`,tr:`waraʿ`,fr:`scrupule religieux, piété`,fm:`Masdar Form I`,root:`و ر ع`},
      {w:`إِحْسَان`,p:`إحسان`,tr:`iḥsān`,fr:`excellence spirituelle (3e niveau)`,fm:`Masdar Form IV`,root:`ح س ن`},
      {w:`تَوَكُّل`,p:`توكل`,tr:`tawakkul`,fr:`confiance en Dieu`,fm:`Masdar Form V`,root:`و ك ل`},
      {w:`صَبْر`,p:`صبر`,tr:`ṣabr`,fr:`patience, endurance`,fm:`Masdar Form I`,root:`ص ب ر`},
      {w:`شُكْر`,p:`شكر`,tr:`shukr`,fr:`gratitude`,fm:`Masdar Form I`,root:`ش ك ر`},
      {w:`قَضَاء وَقَدَر`,p:`قضاء وقدر`,tr:`qaḍāʾ wa-qadar`,fr:`décret divin et prédestination`,fm:`Syntagme théologique`,root:`ق ض و`},
      {w:`بَعْث`,p:`بعث`,tr:`baʿth`,fr:`résurrection`,fm:`Masdar Form I`,root:`ب ع ث`},
      {w:`حِسَاب`,p:`حساب`,tr:`ḥisāb`,fr:`jugement des actes`,fm:`Masdar Form I`,root:`ح س ب`},
      {w:`مِيزَان`,p:`ميزان`,tr:`mīzān`,fr:`balance des actes au Jugement`,fm:`Nom — مِفْعَال`,root:`و ز ن`},
      {w:`صِرَاط`,p:`صراط`,tr:`ṣirāṭ`,fr:`pont sur l'enfer (eschatologie)`,fm:`Nom — فِعَال`,root:`ص ر ط`},
      {w:`أَهْل الْكِتَاب`,p:`أهل الكتاب`,tr:`ahl al-kitāb`,fr:`Gens du Livre (juifs et chrétiens)`,fm:`Idāfa`,root:`أ ه ل`},
      {w:`ذِمِّيّ`,p:`ذمي`,tr:`dhimmī`,fr:`non-musulman sous protection islamique`,fm:`Nisba de ذِمَّة`,root:`ذ م م`},
      {w:`جِزْيَة`,p:`جزية`,tr:`jizya`,fr:`impôt des non-musulmans`,fm:`Nom — فِعْلَة`,root:`ج ز ي`},
      {w:`وَقْف`,p:`وقف`,tr:`waqf`,fr:`fondation pieuse (bien de mainmorte)`,fm:`Masdar Form I`,root:`و ق ف`},
      {w:`زَكَاة الْفِطْر`,p:`زكاة الفطر`,tr:`zakāt al-fiṭr`,fr:`zakat de rupture du jeûne`,fm:`Idāfa`,root:`ف ط ر`},
      {w:`صَدَقَة جَارِيَة`,p:`صدقة جارية`,tr:`ṣadaqa jāriya`,fr:`aumône permanente`,fm:`Syntagme`,root:`ج ر ي`},
      {w:`عُمْرَة`,p:`عمرة`,tr:`ʿumra`,fr:`petite omra (pèlerinage hors saison)`,fm:`Nom — فُعْلَة`,root:`ع م ر`},
      {w:`إِحْرَام`,p:`إحرام`,tr:`iḥrām`,fr:`état de consécration (ḥajj/ʿumra)`,fm:`Masdar Form IV`,root:`ح ر م`},
      {w:`طَوَاف`,p:`طواف`,tr:`ṭawāf`,fr:`circumambulation autour de la Kaaba`,fm:`Masdar Form I`,root:`ط و ف`},
      {w:`كَعْبَة`,p:`كعبة`,tr:`kaʿba`,fr:`la Kaaba (sanctuaire de La Mecque)`,fm:`Nom — فَعْلَة`,root:`ك ع ب`},
      {w:`مَكَّة الْمُكَرَّمَة`,p:`مكة المكرمة`,tr:`Makkat al-Mukarrama`,fr:`La Mecque Sacrée`,fm:`Nom propre`,root:`م ك ك`},
      {w:`مَدِينَة الْمُنَوَّرَة`,p:`مدينة المنورة`,tr:`al-Madīnat al-Munawwara`,fr:`Médine la Lumineuse`,fm:`Nom propre`,root:`ن و ر`},
      {w:`أَهْل السُّنَّة`,p:`أهل السنة`,tr:`ahl as-sunna`,fr:`les Sunnites`,fm:`Idāfa`,root:`س ن ن`}
    ]
  }
];
